### PR TITLE
HTTPS first

### PR DESCRIPTION
**Pull request by via-jordan-sokolic**
Workaround for issue https://github.com/solo-io/gloo/issues/2571
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2571

### CODE REVIEW

**Comment by via-jordan-sokolic** [comment]
Whoops, you're right @kdorosh . Will update the PR adding a Helm value to flip the port order as you suggest.

**Comment by via-jordan-sokolic** [comment]
> we'll want to make the same changes in the following places:
> 
> * https://github.com/solo-io/gloo/blob/v1.3.12/install/helm/gloo/templates/13-ingress-proxy-service.yaml#L12-L17
> * https://github.com/solo-io/gloo/blob/v1.3.12/install/helm/gloo/templates/16-clusteringress-proxy-service.yaml#L13-L18
> * https://github.com/solo-io/gloo/blob/v1.3.12/install/helm/gloo/templates/28-knative-external-proxy-service.yaml#L13-L18
> * https://github.com/solo-io/gloo/blob/v1.3.12/install/helm/gloo/templates/31-knative-internal-proxy-service.yaml#L13-L18

Regarding these additional services, in order for `httpsFirst` to be relevant for them they must first support `extraAnnotations`. 

I'd prefer to leave that additional work out of scope for this PR.

**Comment by kdorosh** [comment]
fair point, agreed that is out of scope

/test

**Pull request merged**
