### PR TITLE
provision to add extra annotations to the deployment templates in helm

### PR DESCRIPTION
**Pull request by bharathnoddy**
# Description
- Changes are made only to the helm deployment templates
- Provision to add extra annotations to deployments
- Altered the logic for Prometheus annotations as it was controlling the whole annotations  

# Context

Unable to add extra annotations to the deployment while using the main chart. 

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4232

### CODE REVIEW

**Review by kdorosh — COMMENTED** [review]
looks good, let's add some helm tests and a changelog file. Thanks for the contribution!

e.g. https://github.com/solo-io/gloo/blob/526805af36e878f8c45eb1e274e93a1cc19d08dd/install/test/helm_test.go#L3663

**Comment by bharathnoddy** [comment]
> looks good, let's add some helm tests and a changelog file. Thanks for the contribution!
> 
> e.g.
> 
> https://github.com/solo-io/gloo/blob/526805af36e878f8c45eb1e274e93a1cc19d08dd/install/test/helm_test.go#L3663

Added the tests and changelog. Not sure why some tests are failing. ( not sure if I did the changelog part correct)

**Comment by kdorosh** [comment]
changelog looks good, just want to make sure we move it into the 1.8.0-beta1 directory

**Comment by bharathnoddy** [comment]
> changelog looks good, just want to make sure we move it into the 1.8.0-beta1 directory

Thank you! Should I move the changelog to 1.8.0-beta1  ? is there anything more expected from my end?

**Comment by kdorosh** [comment]
We need this PR to be up to date with master and passing required checks before merge. To do so:
- update the branch with master
- move the changelog to the 1.8.0-beta1 directory
- ensure the codegen check passes (failure logs https://github.com/solo-io/gloo/runs/2220194933?check_suite_focus=true , it looks like the files edited need `goimport`/`gofmt` to be run)
- ensure the generate versioned docs site check passes (failure logs https://github.com/solo-io/gloo/pull/4464/checks?check_run_id=2220194930 , looks like a bug in our generate versioned docs site check on community PRs, we need a check similar to https://github.com/solo-io/gloo/blob/164105fd86d38cd6aa069ad50cf15c64196c1366/.github/workflows/add-pr-label.yaml#L11-L17 that sets `SKIP_CHANGELOG_GENERATION` env var to `true` [here](https://github.com/solo-io/gloo/blob/90da26bcbb5a50b5f811a3c18fa6247495eaecac/.github/workflows/docs-gen.yaml#L33-L34) to fix)

**Comment by bharathnoddy** [comment]
> We need this PR to be up to date with master and passing required checks before merge. To do so:
> 
> * update the branch with master
> * move the changelog to the 1.8.0-beta1 directory
> * ensure the codegen check passes (failure logs https://github.com/solo-io/gloo/runs/2220194933?check_suite_focus=true , it looks like the files edited need `goimport`/`gofmt` to be run)
> * ensure the generate versioned docs site check passes (failure logs https://github.com/solo-io/gloo/pull/4464/checks?check_run_id=2220194930 , looks like a bug in our generate versioned docs site check on community PRs, we need a check similar to https://github.com/solo-io/gloo/blob/164105fd86d38cd6aa069ad50cf15c64196c1366/.github/workflows/add-pr-label.yaml#L11-L17
>    that sets `SKIP_CHANGELOG_GENERATION` env var to `true` [here](https://github.com/solo-io/gloo/blob/90da26bcbb5a50b5f811a3c18fa6247495eaecac/.github/workflows/docs-gen.yaml#L33-L34) to fix)

I have fixed those 2 failing checks

**Comment by kdorosh** [comment]
your fix wasn't quite right, but I fixed community PRs in https://github.com/solo-io/gloo/pull/4521 . So we should be able to undo your changes to `.github/workflows/docs-gen.yaml` and pull in latest from master, and it lgtm!

**Comment by bharathnoddy** [comment]
> your fix wasn't quite right, but I fixed community PRs in #4521 . So we should be able to undo your changes to `.github/workflows/docs-gen.yaml` and pull in latest from master, and it lgtm!

done

**Review by kdorosh — APPROVED** [review]
🎉  thanks!

**Pull request merged**
