### PR TITLE
support for gzip compression using default values

### PR DESCRIPTION
**Pull request by axhixh**
- added unit test
- added local e2e test

### CODE REVIEW

**Comment by yuval-k** [comment]
while the gzip is enabled on the route extension, it applies to all routes in all vhosts. This makes me think that maybe a good place for it is somewhere else - maybe config to gloo?

cc @axhixh @ilackarms @ilevine

**Comment by axhixh** [comment]
@yuval-k can the filter be enabled per virtual service or is it global?

**Comment by yuval-k** [comment]
I believe it is global. it's normally turned on by http accept header...

**Comment by ilackarms** [comment]
it might be with it to open an issue on envoy to discuss being able to toggle this filter with route / cluster metadata
other than that we'd have to add an api for creating global Envoy config, which i'm not opposed to.

**Comment by ilackarms** [comment]
it makes sense that this config will live inside of the `role` object (which we'll probably rename soon)

**Comment by yuval-k** [comment]
This should be role - closing.

**Pull request closed without merging**
