### PR TITLE
Added in petclinic-vet

### PR DESCRIPTION
**Pull request by scranton**

### CODE REVIEW

**Comment by yuval-k** [comment]
@scranton did you see this https://github.com/solo-io/gloo/blob/master/example/petstore/petstore.yaml  ?

**Comment by scranton** [comment]
@yuval-k yes, I saw petstore.yaml, but thats a different app. petstore is 4 REST function; petclinic is web app. This PR add petclinic-vets so you can show Gloo routing /vets => petclinic-vets.

**Comment by yuval-k** [comment]
right, sorry about the confusion

**Pull request merged**
