### PR TITLE
v1.12.x Set MaxCallSendMsgSize on proxy debug client

### PR DESCRIPTION
**Pull request by Bslabe123**
# Description

Proxy debug client now applies the CallOption grpc.MaxCallRecvMsgSize to GetProxies

# Context

Some customers have proxies that exceed the 100Mb default size limit which would cause 'kubectl get proxies' to error out. We fixed this issue by setting the size limit to the maximum possible (MaxInt32).

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/6630

### CODE REVIEW

**Review by elcasteel — APPROVED** [review]

**Comment by elcasteel** [comment]
Current failure is in the helm unit tests - does this work locally @Bslabe123 ?
`
Step #10 - "test": ------------------------------
Step #10 - "test": • Failure [0.487 seconds]
Step #10 - "test": Helm Test Helm 3 [It] should have all resources marked with a namespace 
Step #10 - "test": /workspace/gloo/install/test/helm_test.go:147
Step #10 - "test": 
Step #10 - "test":   Resource &{Object:map[apiVersion:scheduling.k8s.io/v1 description:Default priority class for all pods globalDefault:true kind:PriorityClass metadata:map[name:default-priority-class] value:1000]} does not have a namespace
Step #10 - "test":   Expected
Step #10 - "test":       <string>: 
Step #10 - "test":   not to be empty`

**Comment by Bslabe123** [comment]
> Current failure is in the helm unit tests - does this work locally @Bslabe123 ? ` Step #10 - "test": ------------------------------ Step #10 - "test": • Failure [0.487 seconds] Step #10 - "test": Helm Test Helm 3 [It] should have all resources marked with a namespace Step #10 - "test": /workspace/gloo/install/test/helm_test.go:147 Step #10 - "test": Step #10 - "test": Resource &{Object:map[apiVersion:scheduling.k8s.io/v1 description:Default priority class for all pods globalDefault:true kind:PriorityClass metadata:map[name:default-priority-class] value:1000]} does not have a namespace Step #10 - "test": Expected Step #10 - "test": <string>: Step #10 - "test": not to be empty`

That shouldnt be there! Removing now

**Review by elcasteel — APPROVED** [review]

**Pull request merged**
