### PR TITLE
Fixed bug that prevents having an http and and an https virtual service on same host

### PR DESCRIPTION
**Pull request by derrickburns**
This fixes the bug that prevents two virtual services on same host, where one serves http and the other serves https.
BOT NOTES: 
resolves https://github.com/solo-io/gloo/pull/734

### CODE REVIEW

**Comment by ilackarms** [comment]
aha! whoopsie! embarassing, thanks for this fix. note you'll have to fix the changelog to make our ci bot happy. you'll need to copy (and modify) one of the existing FIX changelog `.yaml` files into a new `changelog/v0.13.29` dir

**Comment by yuval-k** [comment]
A Test has failed (we are working to make the logs available to the community by using tekton, but for now i'll paste it here):
```
------------------------------
• Failure [0.003 seconds]
Translator merge [It] should not error with one contains ssl config 
/workspace/gopath/src/github.com/solo-io/gloo/projects/gateway/pkg/translator/translator_test.go:209

  Expected
      <[]*v1.VirtualHost | len:1, cap:1>: [
          {
              Name: "gloo-system.name2",
              Domains: ["d1.com"],
              Routes: [
                  {
                      Matcher: {
                          PathSpecifier: {Prefix: "/2"},
                          Headers: nil,
                          QueryParameters: nil,
                          Methods: nil,
                          XXX_NoUnkeyedLiteral: {},
                          XXX_unrecognized: nil,
                          XXX_sizecache: 0,
                      },
                      Action: nil,
                      RoutePlugins: nil,
                      XXX_NoUnkeyedLiteral: {},
                      XXX_unrecognized: nil,
                      XXX_sizecache: 0,
                  },
              ],
              VirtualHostPlugins: nil,
              CorsPolicy: nil,
              XXX_NoUnkeyedLiteral: {},
              XXX_unrecognized: nil,
              XXX_sizecache: 0,
          },
      ]
  to have length 0

  /workspace/gopath/src/github.com/solo-io/gloo/projects/gateway/pkg/translator/translator_test.go:216
------------------------------
SS

Summarizing 1 Failure:

[Fail] Translator merge [It] should not error with one contains ssl config 
/workspace/gopath/src/github.com/solo-io/gloo/projects/gateway/pkg/translator/translator_test.go:216

Ran 13 of 15 Specs in 0.006 seconds
FAIL! -- 12 Passed | 1 Failed | 0 Pending | 2 Skipped
--- FAIL: TestTranslator (0.01s)
FAIL
```

**Comment by derrickburns** [comment]
@yuval-k I believe that these were errors in the tests.  I modified them. Please confirm.

**Pull request merged**
