### PR TITLE
[1.15] FIPS support for SDS

### PR DESCRIPTION
**Pull request by sheidkamp**
# Description

Backport of https://github.com/solo-io/gloo/pull/9065

### CODE REVIEW

**Review by nfuden — DISMISSED** [review]

**Review by sam-heilbron — APPROVED** [review]

**Review by ashishb-solo — APPROVED** [review]

**Comment by sheidkamp** [comment]
Bulldozer comment?

**Comment by sheidkamp** [comment]
bulldozer wake up?

**Comment by sheidkamp** [comment]
comment for dozer

**Pull request merged**
