### PR TITLE
Update Gloo Edge Consul+Vault Docs

### PR DESCRIPTION
**Pull request by inFocus7**
# Description

Update Gloo Edge Docs

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sam-heilbron** [comment]
@inFocus7 I think we're safe to delete this PR and tackle any other docs the next time we encounter this space. What do you think?

**Comment by inFocus7** [comment]
Could we merge these changes actually? They're not much, but I think it could still maybe(?) be helpful for anyone new following the guide(s). Not sure how primarily-docs updated are handled. We could also let doc know or ask them about these. I know for instance the YouTube video linked is broken (it might have been privated)

**Review by sam-heilbron — APPROVED** [review]

**Comment by sam-heilbron** [comment]
LGTM. Leaving the 'work in progress' label intentionally so that this PR doesn't merge. Let's let https://github.com/solo-io/gloo/pull/6452 merge first

**Pull request merged**
