### PR TITLE
[1.13] Expose Envoy's OCSP Stapling Configuration

### PR DESCRIPTION
**Pull request by inFocus7**
**NOTE**: `OCSP Staple` is an `OCSP response` (You're "stapling" an ocsp response), which is why I use them interchangeably.

Backport of #8095 

# Description

This PR adds support for OCSP stapling by exposing Envoy's OCSP configuration. It currently **only** handles storing and using an ocsp response in the static config, **not** automatic rotating/fetching.

It exposes `ocsp_staple` and `ocsp_staple_policy`, which are translated to Envoy's [OCSP Staple](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlscertificate) and [OCSP Staple Policy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/transport_sockets/tls/v3/common.proto#extensions-transport-sockets-tls-v3-tlscertificate).

To store the OCSP staple in a secret, we re-utilized the `TLSSecret` as it contains all the relevant certificates. We also use the `tls.ocsp-staple` data field for storage so it matches [cert-manager](https://github.com/cert-manager/cert-manager)'s **`draft`** PR (5830), and we can work well with it once merged. 

Unit test were created + e2e tests to test that the tls secret + setup with ocsp works as expected. The `x/crypto` is now directly required as it's needed for generating the (fake) ocsp responses used in the tests.

grpcweb tests were updated to use the newer testContext + the tests themselves have been updated to match 1.14+

# Context

Users want OCSP stapling support + it'll be a nice [security performance](https://blog.cloudflare.com/high-reliability-ocsp-stapling/) feature.

# Reproduction

## Envoy Bootstrap

Two scripts `setup.sh` and `teardown.sh`. `setup.sh` goes through the process of creating the certificates, ocsp setup, and python service/server to be used as the upstream.

To run, unzip the folder and do `sh setup.sh` to go through the CA creation process. After that is done, make sure to add the common names to your `/etc/hosts` folder + trust the root CA. Then run `docker-compose up` where it was created. You should be able to hit `https://<client-CN>.com:8000` and get `Hello!` back. After 10 minutes (once the OCSP response expires), you should have issues contacting the upstream. 

_There are more notes in the `setup.sh` script._
_I'm using Gloo's envoy wrapper, as I initially tested this using our [local-gateway-proxy](https://github.com/solo-io/gloo/tree/master/install/local-gateway-proxy)_

[envoy-bootstrap.zip](https://github.com/solo-io/gloo/files/11254835/envoy-bootstrap.zip)

## Gloo
Same as above. Will only set up the certificates, but I added some steps to setup Gloo w/ OCSP using this PR (building it). I did not setup the upstream, since I couldn't get that portion to work, but did verify that OCSP + policy worked as expected using a VS (downstream) + DirectResponse. Testing with a server upstream is more of a sanity check. Will ask someone from field if they're able test/verify this using a full server/upstream setup.

[gloo-oss.zip](https://github.com/solo-io/gloo/files/11288788/gloo-oss.zip)

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by inFocus7** [comment]
Running `go mod tidy` leads to:
```
go: finding module for package github.com/solo-io/gloo/test/testutils
go: finding module for package github.com/solo-io/gloo/test/gomega/matchers
go: finding module for package github.com/onsi/ginkgo/v2
go: found github.com/onsi/ginkgo/v2 in github.com/onsi/ginkgo/v2 v2.9.2
go: finding module for package github.com/solo-io/gloo/test/testutils
go: finding module for package github.com/solo-io/gloo/test/gomega/matchers
github.com/solo-io/gloo/test/e2e tested by
	github.com/solo-io/gloo/test/e2e.test imports
	github.com/solo-io/gloo/test/gomega/matchers: no matching versions for query "latest"
github.com/solo-io/gloo/test/e2e tested by
	github.com/solo-io/gloo/test/e2e.test imports
	github.com/solo-io/gloo/test/testutils: no matching versions for query "latest"
```

so will probably manually tidy based on the codegen results while figuring out my local issue

**Comment by inFocus7** [comment]
Marking as "Ready for review" to ensure everything was backported and all's passing

**Comment by inFocus7** [comment]
Seeing the issue I brought up in `codegen`, so checking what of my backport broke stuff

**Comment by sam-heilbron** [comment]
We do not need to deliver this work into 1.13. Closing.

**Pull request closed without merging**
