### PR TITLE
Ability to specify clusterIP and annotations for gateway service via Helm chart

### PR DESCRIPTION
**Pull request by ewbankkit**
Fixes https://github.com/solo-io/gloo/issues/448.

### CODE REVIEW

**Comment by yuval-k** [comment]
Cc @EItanya

**Comment by ewbankkit** [comment]
I'll add documentation changes in another PR to https://github.com/solo-io/solo-docs.

**Comment by EItanya** [comment]
One quick comment:
The way that this project does helm generation is currently not well documented. tracked via #454 

Essentially our manifests are generated from these helm templates using the make target `manifest`. This make target generates the manifests with the proper versions using the script `generate.go`. This script unmarshals the values-templates via the values present in `values.go` and then creates the permanent `values.yaml` files. In order for values-template changes to be picked up, any changes to the values templates need to be added to the `values.go` file located in the `generate` folder of the helm chart.

Let me know if you have any questions about this.

Thanks again

**Comment by ewbankkit** [comment]
@EItanya Thanks for that; It was working in my tests as the new values I introduced had no default values in the `values-template` files.
Anyway, I made the changed suggested and rebased to remove the conflict.

**Comment by EItanya** [comment]
@ewbankkit thanks so much for the quick fix. We plan on introducing a test very soon that will check for unused values in the templates to avoid this exact issue. As usual any help is greatly appreciated.

Thanks again!

**Pull request merged**
