### PR TITLE
Update install docs to use correct rbac override

### PR DESCRIPTION
**Pull request by kdorosh**
the old format is still documented, fix

### CODE REVIEW

**Comment by kdorosh** [comment]
might also need to update `Namespaced` to be lower case

**Comment by mitchdraft** [comment]
@kdorosh capital `Namespaced` is correct (though inconsistent with other values)
https://github.com/solo-io/gloo/blob/master/install/helm/gloo/generate/values.go#L38
(same is true on feature-rc1)

It would probably be worth lowercasing that with the other feature-rc1 changes, I'll make an issue

**Comment by kdorosh** [comment]
For clarity, capital `Namespaced` is actually incorrect but it's auto-generated, and we are handling that fix here: https://github.com/solo-io/gloo/pull/1570

**Pull request merged**
