### PR TITLE
[DNM] Feat/k8s 125

### PR DESCRIPTION
**Pull request by nfuden**
See https://github.com/solo-io/solo-projects/pull/4358

Feels safe to rip out klog setting from https://github.com/solo-io/gloo/pull/1880
This is due to the following: klog now defaults to log to stderr after v0.4.0 and if any dep pulls in v0.4.0 it will correctly fail https://github.com/kubernetes-sigs/controller-runtime/issues/1607

### CODE REVIEW

**Comment by nfuden** [comment]
/kick  WARNING: DATA RACE
Step #10 - "test": Read at 0x00c00094812c by goroutine 81:
Step #10 - "test":   github.com/solo-io/gloo/projects/gloo/pkg/validation_test.glob..func1.4.3.1()

**Comment by nfuden** [comment]
/kick data race again. Need to fix it either way but using this to determine if its a flake or a true 100 percent error

**Comment by nfuden** [comment]
/kick hey build bot why arent you picking this change up

**Comment by jenshu** [comment]
closing in favor of https://github.com/solo-io/gloo/pull/8024

**Pull request closed without merging**
