### PR TITLE
fix auth config update

### PR DESCRIPTION
**Pull request by ashleywang1**
# Description

When AuthConfigs are updated, gloo resyncs, which should trigger a gateway resync as well. Previously, we weren't adding AuthConfigs into the hash that decided whether the gloo snapshot changed or not. That has been fixed here.

# Context

Users ran into this bug when deploying an auth config after a virtual service.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2920

### CODE REVIEW

**Comment by ashleywang1** [comment]
/kick regression-test flake https://console.cloud.google.com/cloud-build/builds/1314e7bb-7700-47fd-ab75-1e8dcac68be6?project=solo-public

**Comment by arianaw66** [comment]
/kick "[Fail] Kube2e: gateway tests with virtual service with a mix of valid and invalid virtual services [BeforeEach] preserves the valid virtual services in envoy when a virtual service has been made invalid"

**Comment by ashleywang1** [comment]
/kick  [Fail] Kube2e: gateway with subsets and upstream groups [It] routes to subsets and upstream groups  gateway-test flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=4d28542e-5c35-4653-a66c-cb6928c3fa5e

**Comment by ashleywang1** [comment]
/kick [Fail] Robustness tests [It] updates Envoy endpoints even if proxy is rejected https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=8fc84db7-232e-4dc8-8baa-50a6dd7e1d4f

**Comment by ashleywang1** [comment]
/kick  [Fail] Kube2e: Ingress [It] works  error https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=91caca2d-7e71-4c88-8623-5428c7503898

**Pull request merged**
