### PR TITLE
feat: add AWS cloudmap upstream

### PR DESCRIPTION
**Pull request by mwieczorek**
# Description

This PR introduces a new upstream type: AWS CloudMap.

# Context

ref: https://github.com/solo-io/gloo/issues/7304

This is only a proposal of how a new upstream type could be implemented. I'd like to treat it as a starting point of discussion (apologise for not following strictly the 'contributing guidelines').

Example resource:

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: test
  namespace: test
spec:
  cloudmap:
    cloudmapNamespaceName: "mesh-gloo" # required
    serviceName: "cloudmap-service-name" #required
    port: 8080 # required
    awsAccountId: "617007418524" # optional
    assumeRoleName: "cloudmap_gloo" #optional
```

Based on the spec.cloudmap fields (namespace name, service name, port), gloo will look for AWS CloudMap namespace/service and create endpoints (based on the list of instances and returned IPs).
Optional fields (account ID, assume role name) are useful in case of multiple account setup (where upstream service is deployed in another account) - in such case gloo needs to assume role in defined account to 'query' CloudMap.

Tested with EKS and upstream services deployed in a different account.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sam-heilbron** [comment]
@mwieczorek thanks for opening this PR! I see "This is only a proposal of how a new upstream type could be implemented. I'd like to treat it as a starting point of discussion". I'd like to chat with some folks internally about this proposal and we can get back to you next week on the next steps for this work. How does that sound to you?

**Comment by mwieczorek** [comment]
Sounds great @sam-heilbron !
I'm waiting for your feedback after internal conversations.
Btw: if you prefer more 'sync' mode, you can find me in solo-io slack :)

**Comment by sam-heilbron** [comment]
@mwieczorek Apologies for the delay. We still haven't had the internal discussion yet, but there has been a number of people interested in discussing. Around the holidays it may be harder to schedule this but I'll try to keep progress on this and keep you updated on the discussions

**Comment by sam-heilbron** [comment]
Thanks for the contribution @mwieczorek ! I spoke with @bensolo-io and he will be responsible for gathering more context about this feature request and making a plan of action. I believe he has communicated this to you. 

We're going to close this PR for now, and will track all future work in https://github.com/solo-io/gloo/issues/7304

**Pull request closed without merging**
