### PR TITLE
Support for custom cluster dns name

### PR DESCRIPTION
**Pull request by unbreakab1e**
Hi! We were investigating the possibility to use Gloo as an API Gateway in a newly provisioned cluster. Suddenly we've stumbled upon an issue with the Basic Routing Example being dysfunctional. It seems that the Helm Chart considers that cluster DNS name is *always* `cluster.local`, but in our sandbox cluster (provisioned with Kubespray) we changed it to `dev-sandbox.local`.
As a result no matter how many routes or virtualservices one will create, envoy would never listen on proxy port 8080 -- simply because it could not connect to control plane and retrieve the configuration. 
This PR adds a new value to the chart, `k8s.cluster-name`, so one might override this default behavior.

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/754

### CODE REVIEW

**Comment by marcogschmidt** [comment]
Hi @unbreakab1e, thank you for the contribution! There are couple of things that need to be added before this PR can be merged:

1. You need to add a changelog entry documenting your fix. If you look at the `changelog` directory at the repository root you will find lots of examples. The appropriate entry type in this case is `FIX`, which will require you to provide a link to a GitHub issue. I have just created [an issue](https://github.com/solo-io/gloo/issues/754) you can link to.
2. The template value files you updated (`values-*-template.yaml`) are used to generate the actual value files at build time. The generation happens in [`install/helm/gloo/generate.go`](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/generate.go). The template files are parsed to a go struct, updated based on the build context and then serialized back to the final value files. You have to add a new field representing the new `k8s.cluster-name` attribute to the `Config` struct in [`install/helm/gloo/generate/values.go`](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/generate/values.go), otherwise it will be ignored.

Could you please address these two issues? Hope the explanation is clear, feel free to ask any question otherwise.

I also found the `cluster.local` string hardcoded in two of our Gloo plugins ([here](https://github.com/solo-io/gloo/blob/fe5d3a4e0cc0888c5cedd941faeb38f2749cb11f/projects/gloo/pkg/plugins/kubernetes/plugin.go#L28) and [here](https://github.com/solo-io/gloo/blob/fe5d3a4e0cc0888c5cedd941faeb38f2749cb11f/projects/gloo/pkg/plugins/linkerd/plugin.go#L135)) and am currently looking into how to fix those as well.

**Comment by marcogschmidt** [comment]
Tests failed because the new variable name contains a hyphen. We use camel case for variables (in accordance with [Helm best practices](https://helm.sh/docs/chart_best_practices/#naming-conventions)). Could you rename it to `clusterName`?

**Comment by unbreakab1e** [comment]
Hello @marcogschmidt , thanks for the clarifications, I will address those issues in the upcoming days and update the PR.

**Comment by marcogschmidt** [comment]
@unbreakab1e build failed with this error:
```
# github.com/solo-io/gloo/install/helm/gloo/generate
install/helm/gloo/generate/values.go:14:18: undefined: K8s
make: *** [/workspace/gopath/src/github.com/solo-io/gloo/_output/.generated-code] Error 2
```
The `K8s` type is undefined, you need to add something like this:
```go
type K8s struct {
  ClusterName string `json:"clusterName"`
}
```

To verify that everything works you can run `make manifest` from the project root to generate the value files. Also, I'd run `make generated-code -B` locally just to make sure that the branch build won't fail on formattatting issues.

**Pull request closed without merging**
