### PR TITLE
Add CONNECT Support

### PR DESCRIPTION
**Pull request by hunshcn**
# Description

Add connect matcher, add CONNECT upgrade type to hcm and route

# Context

https://github.com/solo-io/gloo/issues/7914

Gloo cannot set connect options to envoy, such as upgrade type or connect matcher. Cannot serve a forwarding proxy backend.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7914

### CODE REVIEW

**Review by kdorosh — DISMISSED** [review]

**Review by gunnar-solo — APPROVED** [review]

**Comment by hunshcn** [comment]
> When I kicked the `build-bot` build several times using the `/test` directive I hit
> 
> Two failures:
> 
> * [failure 1](https://console.cloud.google.com/cloud-build/builds;region=global/64c52c25-eea9-452d-9af5-8538af978f23;step=1?project=solo-public)
> * [failure 2](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=e18f1063-877d-49c5-859e-ebfe2a5eec29)
> 
> as well as one [legitimate flake](https://console.cloud.google.com/cloud-build/builds;region=global/351eab32-5881-43f9-bd7b-0ff0ccbebf0b;step=1?project=solo-public)

fixed

**Review by kdorosh — APPROVED** [review]

**Pull request merged**
