### PR TITLE
Istio 1.22 support

### PR DESCRIPTION
**Pull request by sheidkamp**
# Description
* Changes to support Istio 1.22.0
* Pull Istio versions from env files for pr-kubernetes-test and nightly e2e workflows

## CI changes
* Update `setup-kind.sh` and kube2e test artifacts to use Istio 1.22.0
* Update nightly e2e tests to pull Istio versions from the min/max env files defined in test matrix.
* Update pr-kubernetes-test workflow to pull Istio version from env file.
* Update setup-kind-cluster composite action to have `istio-version` input, and set it as an ENV variable when calling setup-kind.sh

## Docs changes
Updated supported versions

## Context
[Istio 1.22 Upgrade Notes](https://istio.io/latest/news/releases/1.22.x/announcing-1.22/upgrade-notes/)
[Istio 1.22 Change Notes](https://istio.io/latest/news/releases/1.22.x/announcing-1.22/change-notes/)
Brief discussion of the Delta XDS "on by default" changes: https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1716563532092069?thread_ts=1716562982.928539&cid=G01EERAK3KJ

## Testing
We are relying on the existing CI to validate that expected functionality is not broken.

### Validating CI/matrix changes
[Istio version set in in pr-regression-tests (cluster_one as example)](https://github.com/solo-io/gloo/actions/runs/9292517764/job/25573601320?pr=9539#step:6:62): `ISTIO_VERSION: 1.22.0` is set in environment when calling `setup-kind.sh`

Manual run of nightly k8s e2e tests
* [min](https://github.com/solo-io/gloo/actions/runs/9292551524/job/25573698630#step:5:57): `ISTIO_VERSION: 1.16.7`
* [max](https://github.com/solo-io/gloo/actions/runs/9292551524/job/25573698838#step:5:69): `ISTIO_VERSION: 1.22.0`

### CODE REVIEW

**Comment by sheidkamp** [comment]
/kick

```
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m------------------------------[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;9m• [FAILED] [0.421 seconds][0m
Step #1 - "run-tests": Step #7 - "run-tests": [0mKubernetes Gateway API integration [38;5;243mwhen kube gateway integration is enabled [38;5;9m[1m[It] renders default GatewayParameters[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m/workspace/gloo/install/test/k8sgateway_test.go:57[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9m[FAILED] Expected
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 5
Step #1 - "run-tests": Step #7 - "run-tests":   to equal
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 1[0m
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/workspace/gloo/install/test/k8sgateway_test.go:71[0m [38;5;243m@ 05/29/24 20:26:09.348[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mFull Stack Trace[0m
Step #1 - "run-tests": Step #7 - "run-tests":     github.com/solo-io/gloo/install/test.init.func4.1.3.3()
Step #1 - "run-tests": Step #7 - "run-tests":     	/workspace/gloo/install/test/k8sgateway_test.go:71 +0x403
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m------------------------------[0m
```

**Review by artberger — APPROVED** [review]

**Comment by sheidkamp** [comment]
/kick

```
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;9m• [FAILED] [0.414 seconds][0m
Step #1 - "run-tests": Step #7 - "run-tests": [0mKubernetes Gateway API integration [38;5;243mwhen kube gateway integration is enabled [38;5;9m[1m[It] renders default GatewayParameters[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m/workspace/gloo/install/test/k8sgateway_test.go:57[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9m[FAILED] Expected
Step #1 - "run-tests": Step #7 - "run-tests":       <string>: 1.22.0
Step #1 - "run-tests": Step #7 - "run-tests":   to equal
Step #1 - "run-tests": Step #7 - "run-tests":       <string>: 1.21.2[0m
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/workspace/gloo/install/test/k8sgateway_test.go:82[0m [38;5;243m@ 05/29/24 20:45:06.851[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mFull Stack Trace[0m
Step #1 - "run-tests": Step #7 - "run-tests":     github.com/solo-io/gloo/install/test.init.func4.1.3.3()
Step #1 - "run-tests": Step #7 - "run-tests":     	/workspace/gloo/install/test/k8sgateway_test.go:82 +0xf4c
```

**Comment by sheidkamp** [comment]
/kick (again)

```
Step #1 - "run-tests": Step #7 - "run-tests": [0mKubernetes Gateway API integration [38;5;243mwhen kube gateway integration is enabled [38;5;9m[1m[It] renders default GatewayParameters[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m/workspace/gloo/install/test/k8sgateway_test.go:57[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9m[FAILED] Expected
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 5
Step #1 - "run-tests": Step #7 - "run-tests":   to equal
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 1[0m
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/workspace/gloo/install/test/k8sgateway_test.go:71[0m [38;5;243m@ 05/29/24 21:04:49.182[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mFull Stack Trace[0m
Step #1 - "run-tests": Step #7 - "run-tests":     github.com/solo-io/gloo/install/test.init.func4.1.3.3()
Step #1 - "run-tests": Step #7 - "run-tests":     	/workspace/gloo/install/test/k8sgateway_test.go:71 +0x403
```

**Comment by sheidkamp** [comment]
/kick - same one we've been seeing

```
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;9m• [FAILED] [0.419 seconds][0m
Step #1 - "run-tests": Step #7 - "run-tests": [0mKubernetes Gateway API integration [38;5;243mwhen kube gateway integration is enabled [38;5;9m[1m[It] renders default GatewayParameters[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m/workspace/gloo/install/test/k8sgateway_test.go:57[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9m[FAILED] Expected
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 5
Step #1 - "run-tests": Step #7 - "run-tests":   to equal
Step #1 - "run-tests": Step #7 - "run-tests":       <uint32>: 1[0m
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mIn [1m[It][0m[38;5;9m at: [1m/workspace/gloo/install/test/k8sgateway_test.go:71[0m [38;5;243m@ 05/29/24 22:27:06.988[0m
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests":   [38;5;9mFull Stack Trace[0m
Step #1 - "run-tests": Step #7 - "run-tests":     github.com/solo-io/gloo/install/test.init.func4.1.3.3()
Step #1 - "run-tests": Step #7 - "run-tests":     	/workspace/gloo/install/test/k8sgateway_test.go:71 +0x403
```

**Review by sam-heilbron — APPROVED** [review]
LGTM!

**Review by artberger — APPROVED** [review]

**Pull request merged**
