### PR TITLE
Feature/add shortname to crds

### PR DESCRIPTION
**Pull request by antonioberben**
# Description

Add a another shortname to VirtualService so I can use `kubectl get gvs -A` to list all VS resources.

When Istio is installed, the shortname and the resource name collides.

# Context

Having Istio and GE isntalled, a user listing all Istio VS resources has to:

```
kubectl get virtualservices.networking.istio.io -A
```

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by antonioberben** [comment]
Agreed with @sam-heilbron , change will apply to all CRDs to be consistent

**Review by kdorosh — CHANGES_REQUESTED** [review]
the crd files you have edited here are generated by solokit. the source of truth is [here](https://github.com/solo-io/gloo/blob/e06fa4697f39256aa031afc4695c9e3bc8f96ff2/projects/gateway/api/v1/gateway.proto#L25), for example

not sure off the top of my head, but we might need to update solokit support to add multiple short names

can point you towards tests once the implementation is working

**Comment by kdorosh** [comment]
per @sam-heilbron 

> This is passing codgen because our CRD generation isn't entirely handled by solo-kit yet (though it would be good to). Right now we just take the CRD, re-gen the schemas and then modify the schemas. That is why we could manually change the shortname without codegen failures

**Comment by sam-heilbron** [comment]
@antonioberben is this ready for review?

**Comment by antonioberben** [comment]
@sam-heilbron , if we are ok for the auto-generated CRDs topic and I do not need to add tests out of this changes, I think yes. I will wait for your thumbsup regarding this two points. Thank you

**Review by kdorosh — APPROVED** [review]

**Pull request merged**
