### PR TITLE
fix: AWS transformations work together with regular transformations

### PR DESCRIPTION
**Pull request by yuval-k**
# Description

~~Note: ci will fail until https://github.com/solo-io/envoy-gloo/pull/151 is merged and released.~~

Create a transformation stage for AWS transformations, so it can be used together with regular transformations.
Updated envoy is needed, as new transformation config is added to keep compatibility with the existing transform.

# Context
Related:
- https://github.com/solo-io/gloo/issues/5985
- https://github.com/solo-io/gloo/issues/6062

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5985

### CODE REVIEW

**Comment by yuval-k** [comment]
/kick ci crazy?! never saw this one
image

**Comment by yuval-k** [comment]
/kick
added permissions in CI to call the new `echo` functions

**Comment by yuval-k** [comment]
data race?!
```
WARNING: DATA RACE
Write at 0x00c00059fc80 by goroutine 74:
  runtime.mapassign()
      /usr/local/go/src/runtime/map.go:571 +0x0
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypeWithName()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme.go:196 +0x3d5
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddKnownTypes()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme.go:170 +0x284
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).Register.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/scheme/scheme.go:72 +0xab
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme_builder.go:29 +0xa1
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/scheme/scheme.go:87 +0x7a
  github.com/solo-io/solo-apis/pkg/api/ratelimit.solo.io/v1alpha1.AddToScheme()
      /go/pkg/mod/github.com/solo-io/solo-apis@v0.0.0-20210922150112-505473b2e66c/pkg/api/ratelimit.solo.io/v1alpha1/register.go:32 +0x4b
  github.com/solo-io/solo-apis/pkg/api/ratelimit.solo.io/v1alpha1.NewClientsetFromConfig()
      /go/pkg/mod/github.com/solo-io/solo-apis@v0.0.0-20210922150112-505473b2e66c/pkg/api/ratelimit.solo.io/v1alpha1/clients.go:52 +0x85
  github.com/solo-io/gloo/projects/gloo/pkg/api/external/solo/ratelimit.NewRateLimitClients()
      /workspace/gloo/projects/gloo/pkg/api/external/solo/ratelimit/extensions.go:54 +0x11e
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.RunGlooWithExtensions()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:418 +0xadb
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.RunGloo()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:334 +0x1f7
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.(*setupSyncer).Setup()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:319 +0x854
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.(*setupSyncer).Setup-fm()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:181 +0xab
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.glob..func1.4.4.6.1()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer_test.go:223 +0x163
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:337 +0xd8
  github.com/onsi/gomega/matchers.(*PanicMatcher).Match()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/matchers/panic_matcher.go:50 +0x215
  github.com/onsi/gomega/internal.(*Assertion).match()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/assertion.go:64 +0x94
  github.com/onsi/gomega/internal.(*Assertion).To()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/assertion.go:38 +0x117
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.glob..func1.4.4.6()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer_test.go:223 +0x3ca
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xfc
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x184
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0xb9
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x7fd
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0x187
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0x17b
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x235
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0x145
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x839
  github.com/onsi/ginkgo.runSpecsWithCustomReporters()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x357
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.TestSetup()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_suite_test.go:14 +0x172
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Previous read at 0x00c00059fc80 by goroutine 50:
  runtime.mapaccess2()
      /usr/local/go/src/runtime/map.go:452 +0x0
  k8s.io/apimachinery/pkg/runtime.(*Scheme).New()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme.go:318 +0xb4
  k8s.io/apimachinery/pkg/runtime.UseOrCreateObject()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/codec.go:97 +0xc6
  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/serializer/json/json.go:259 +0x497
  k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/helper.go:252 +0xac
  k8s.io/apimachinery/pkg/runtime.(*WithoutVersionDecoder).Decode()
      <autogenerated>:1 +0xd9
  k8s.io/apimachinery/pkg/runtime.Decode()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/codec.go:58 +0x297
  k8s.io/client-go/rest/watch.(*Decoder).Decode()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/watch/decoder.go:62 +0x206
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/watch/streamwatcher.go:105 +0x168

Goroutine 74 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:45 +0x236

Goroutine 50 (finished) created at:
  k8s.io/apimachinery/pkg/watch.NewStreamWatcher()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/watch/streamwatcher.go:76 +0x1a5
  k8s.io/client-go/rest.(*Request).newStreamWatcher()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/request.go:775 +0x5e4
  k8s.io/client-go/rest.(*Request).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/request.go:720 +0x5d0
  k8s.io/client-go/kubernetes/typed/core/v1.(*endpoints).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/kubernetes/typed/core/v1/endpoints.go:112 +0x2c8
  k8s.io/client-go/informers/core/v1.NewFilteredEndpointsInformer.func2()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/informers/core/v1/endpoints.go:71 +0x25c
  k8s.io/client-go/tools/cache.(*ListWatch).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/listwatch.go:111 +0x98
  k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:414 +0x6dc
  k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:221 +0x53
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:155 +0x75
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:156 +0xba
  k8s.io/client-go/tools/cache.(*Reflector).Run()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:220 +0x2b5
  k8s.io/client-go/tools/cache.(*Reflector).Run-fm()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:218 +0x54
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:56 +0x45
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:73 +0x6d
==================
==================
WARNING: DATA RACE
Write at 0x00c00059fce0 by goroutine 74:
  runtime.mapassign()
      /usr/local/go/src/runtime/map.go:571 +0x0
  k8s.io/apimachinery/pkg/runtime.(*Scheme).AddUnversionedTypes()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme.go:150 +0x312
  k8s.io/apimachinery/pkg/apis/meta/v1.AddToGroupVersion()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/apis/meta/v1/register.go:75 +0x6b2
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).Register.func1()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/scheme/scheme.go:73 +0xfa
  k8s.io/apimachinery/pkg/runtime.(*SchemeBuilder).AddToScheme()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme_builder.go:29 +0xa1
  sigs.k8s.io/controller-runtime/pkg/scheme.(*Builder).AddToScheme()
      /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.3/pkg/scheme/scheme.go:87 +0x7a
  github.com/solo-io/solo-apis/pkg/api/ratelimit.solo.io/v1alpha1.AddToScheme()
      /go/pkg/mod/github.com/solo-io/solo-apis@v0.0.0-20210922150112-505473b2e66c/pkg/api/ratelimit.solo.io/v1alpha1/register.go:32 +0x4b
  github.com/solo-io/solo-apis/pkg/api/ratelimit.solo.io/v1alpha1.NewClientsetFromConfig()
      /go/pkg/mod/github.com/solo-io/solo-apis@v0.0.0-20210922150112-505473b2e66c/pkg/api/ratelimit.solo.io/v1alpha1/clients.go:52 +0x85
  github.com/solo-io/gloo/projects/gloo/pkg/api/external/solo/ratelimit.NewRateLimitClients()
      /workspace/gloo/projects/gloo/pkg/api/external/solo/ratelimit/extensions.go:54 +0x11e
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.RunGlooWithExtensions()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:418 +0xadb
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.RunGloo()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:334 +0x1f7
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.(*setupSyncer).Setup()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:319 +0x854
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup.(*setupSyncer).Setup-fm()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer.go:181 +0xab
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.glob..func1.4.4.6.1()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer_test.go:223 +0x163
  runtime.call16()
      /usr/local/go/src/runtime/asm_amd64.s:550 +0x3d
  reflect.Value.Call()
      /usr/local/go/src/reflect/value.go:337 +0xd8
  github.com/onsi/gomega/matchers.(*PanicMatcher).Match()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/matchers/panic_matcher.go:50 +0x215
  github.com/onsi/gomega/internal.(*Assertion).match()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/assertion.go:64 +0x94
  github.com/onsi/gomega/internal.(*Assertion).To()
      /go/pkg/mod/github.com/onsi/gomega@v1.16.0/internal/assertion.go:38 +0x117
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.glob..func1.4.4.6()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_syncer_test.go:223 +0x3ca
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xfc
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x184
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0xb9
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x7fd
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0x187
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0x17b
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x235
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0x145
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x839
  github.com/onsi/ginkgo.runSpecsWithCustomReporters()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x357
  github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters()
      /go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/syncer/setup_test.TestSetup()
      /workspace/gloo/projects/gloo/pkg/syncer/setup/setup_suite_test.go:14 +0x172
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Previous read at 0x00c00059fce0 by goroutine 50:
  runtime.mapaccess2()
      /usr/local/go/src/runtime/map.go:452 +0x0
  k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/scheme.go:289 +0x3ac
  k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/serializer/json/json.go:237 +0xbf8
  k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/runtime/serializer/streaming/streaming.go:107 +0x2b1
  k8s.io/client-go/rest/watch.(*Decoder).Decode()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/watch/decoder.go:49 +0xf1
  k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/watch/streamwatcher.go:105 +0x168

Goroutine 74 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:45 +0x236

Goroutine 50 (finished) created at:
  k8s.io/apimachinery/pkg/watch.NewStreamWatcher()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/watch/streamwatcher.go:76 +0x1a5
  k8s.io/client-go/rest.(*Request).newStreamWatcher()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/request.go:775 +0x5e4
  k8s.io/client-go/rest.(*Request).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/rest/request.go:720 +0x5d0
  k8s.io/client-go/kubernetes/typed/core/v1.(*endpoints).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/kubernetes/typed/core/v1/endpoints.go:112 +0x2c8
  k8s.io/client-go/informers/core/v1.NewFilteredEndpointsInformer.func2()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/informers/core/v1/endpoints.go:71 +0x25c
  k8s.io/client-go/tools/cache.(*ListWatch).Watch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/listwatch.go:111 +0x98
  k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:414 +0x6dc
  k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:221 +0x53
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:155 +0x75
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:156 +0xba
  k8s.io/client-go/tools/cache.(*Reflector).Run()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:220 +0x2b5
  k8s.io/client-go/tools/cache.(*Reflector).Run-fm()
      /go/pkg/mod/k8s.io/client-go@v0.22.4/tools/cache/reflector.go:218 +0x54
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:56 +0x45
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /go/pkg/mod/k8s.io/apimachinery@v0.22.4/pkg/util/wait/wait.go:73 +0x6d
==================
```

**Comment by yuval-k** [comment]
/kick
filed https://github.com/solo-io/solo-apis/issues/339 for the data race

**Comment by yuval-k** [comment]
/kick
consul data race
```
•==================
WARNING: DATA RACE
Write at 0x00c000f82060 by goroutine 385:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:294 +0x484
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpointsFromSpecs()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:198 +0x1e4
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:98 +0x584

Previous write at 0x00c000f82060 by goroutine 195:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:294 +0x484
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpointsFromSpecs()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:198 +0x1e4
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:98 +0x584

Goroutine 385 (running) created at:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:59 +0x75b
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*EndpointDiscovery).StartEds()
      /workspace/gloo/projects/gloo/pkg/discovery/discovery.go:177 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*syncer).Sync()
      /workspace/gloo/projects/gloo/pkg/discovery/run.go:49 +0x3d8
  github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*edsEventLoop).Run.func1()
      /workspace/gloo/projects/gloo/pkg/api/v1/eds_event_loop.sk.go:84 +0x2e5

Goroutine 195 (finished) created at:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:59 +0x75b
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*EndpointDiscovery).StartEds()
      /workspace/gloo/projects/gloo/pkg/discovery/discovery.go:177 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*syncer).Sync()
      /workspace/gloo/projects/gloo/pkg/discovery/run.go:49 +0x3d8
  github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*edsEventLoop).Run.func1()
      /workspace/gloo/projects/gloo/pkg/api/v1/eds_event_loop.sk.go:84 +0x2e5
==================
==================
WARNING: DATA RACE
Write at 0x00c001294b88 by goroutine 385:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:294 +0x49c
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpointsFromSpecs()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:198 +0x1e4
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:98 +0x584

Previous write at 0x00c001294b88 by goroutine 195:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:294 +0x49c
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.buildEndpointsFromSpecs()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:198 +0x1e4
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:98 +0x584

Goroutine 385 (running) created at:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:59 +0x75b
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*EndpointDiscovery).StartEds()
      /workspace/gloo/projects/gloo/pkg/discovery/discovery.go:177 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*syncer).Sync()
      /workspace/gloo/projects/gloo/pkg/discovery/run.go:49 +0x3d8
  github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*edsEventLoop).Run.func1()
      /workspace/gloo/projects/gloo/pkg/api/v1/eds_event_loop.sk.go:84 +0x2e5

Goroutine 195 (finished) created at:
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints()
      /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:59 +0x75b
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*EndpointDiscovery).StartEds()
      /workspace/gloo/projects/gloo/pkg/discovery/discovery.go:177 +0x1ea
  github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*syncer).Sync()
      /workspace/gloo/projects/gloo/pkg/discovery/run.go:49 +0x3d8
  github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*edsEventLoop).Run.func1()
      /workspace/gloo/projects/gloo/pkg/api/v1/eds_event_loop.sk.go:84 +0x2e5
==================
```

**Comment by nfuden** [comment]
/kick do i not have permissions when interacting with your prs?

**Comment by yuval-k** [comment]
> /kick do i not have permissions when interacting with your prs?

idk i think i also had issues with kick.. maybe the bot is not feeling well..

**Review by kdorosh — APPROVED** [review]

**Review by sam-heilbron — APPROVED** [review]
LGTM!

**Pull request merged**
