### PR TITLE
Solo-kit and go-utils update

### PR DESCRIPTION
**Pull request by Bslabe123**
# Description

Updated solo-kit and go-utils to their latest versions

# Context

go-utils bump also fixes https://github.com/solo-io/go-utils/issues/475

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sam-heilbron — COMMENTED** [review]
What behavioral changes do we pull in with this bump of solo-kit? Are there tests we can add to Gloo Edge to verify that it is working as expected?

**Comment by ben-taussig-solo** [comment]
> What behavioral changes do we pull in with this bump of solo-kit? Are there tests we can add to Gloo Edge to verify that it is working as expected?

Here, we bump solo-kit from v0.30.0 to v0.30.2 -- In master, it seems like we don't add any new tests along with the most recent parallel solo-kit bumps (see [here](https://github.com/solo-io/gloo/commit/872b99af17d3a37c8400ce0affcc6b30ff783878)). Additionally, gloo CI is passing, so I think it's probably safe to leave this PR as is.

The functionality included in this solo-kit bump is here: https://github.com/solo-io/solo-kit/compare/v0.30.0...v0.30.2
It's essentially just 2 PRs

**Review by sam-heilbron — COMMENTED** [review]
In the original PR that bumped go-utils to pull in the logging handler npe fix (https://github.com/solo-io/gloo/pull/6709), I added logic to one of our kube2e tests to hit the logging endpoint. The idea was that this test will only pass if the request can be made. Since it's recommended in our production docs I think it's valuable that we have automated testing to confirm that it works. Can we add the same check to this branch as well?

**Review by ben-taussig-solo — APPROVED** [review]
1:1 with the v1.10.x PR that was just approved (see [here](https://github.com/solo-io/gloo/pull/6807)) aside from the auto generated files, so this looks good to me!

**Pull request merged**
