### PR TITLE
Clean up developer portal resources when no release object is present

### PR DESCRIPTION
**Pull request by marcogschmidt**
## Description

Added the `app: dev-portal` label to the label selector that `glooctl uninstall` uses when determining which resources need to be cleaned up in case no release object is present (this happens when uses did not install via `helm install` or `glooctl install`, but instead used `glooctl install gateway --dry-run | kubectl apply -f -`.

## Context

Users ran into this bug when running `glooctl install` after having run `glooctl uninstall -all` to remove a Gloo instance that presumably had been installed via `kubectl apply`. "Presumably" because the issue does not contain information about the way Gloo was installed in the first place and I was not able to reproduce when installoing with `glooctl` or `helm`:

image

(`vals.yaml` contains just `devPortal.enabled: true`)

## Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] I have added tests that prove my fix is effective or that my feature works. (**Note**: existing tests already covered the change)

### CODE REVIEW

**Comment by marcogschmidt** [comment]
[Build](https://console.cloud.google.com/cloud-build/builds/4135be6a-3f15-44e6-b3da-a51817677ef8;step=9?project=solo-public) failed with this error:
```
Kubernetes kubernetes [It] uses json keys when serializing 
/workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go:151

  Expected
      <v1.UpstreamList | len:0, cap:0>: nil
  to have length 2

  /workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go:165

  Full Stack Trace
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes_test.glob..func1.2.3()
  	/workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go:165 +0xb52
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0003a4ea0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/leafnodes/runner.go:113 +0xe0
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0003a4ea0, 0xc00054b0e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/leafnodes/runner.go:64 +0x108
  github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc0005ecb40, 0x2a3ad20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/leafnodes/it_node.go:26 +0x88
  github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc0004bcff0, 0x0, 0x2a3ad20, 0xc00054b0c0)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/spec/spec.go:215 +0x6e2
  github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc0004bcff0, 0x2a3ad20, 0xc00054b0c0)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/spec/spec.go:138 +0x168
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000158780, 0xc0004bcff0, 0x10)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/specrunner/spec_runner.go:200 +0x173
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000158780, 0x1)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/specrunner/spec_runner.go:170 +0x217
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000158780, 0x8)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/specrunner/spec_runner.go:66 +0x141
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0005f0b40, 0x7fce6809a110, 0xc00005f400, 0x27096fd, 0x10, 0xc00030aac0, 0x1, 0x1, 0x2aa7b60, 0xc00054b0c0, ...)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/internal/suite/suite.go:62 +0x6a0
  github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x2a3c380, 0xc00005f400, 0x27096fd, 0x10, 0xc0000cded8, 0x1, 0x1, 0x2d38a88)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/ginkgo_dsl.go:226 +0x339
  github.com/onsi/ginkgo.RunSpecs(0x2a3c380, 0xc00005f400, 0x27096fd, 0x10, 0x0)
  	/go/pkg/mod/github.com/onsi/ginkgo@v1.11.0/ginkgo_dsl.go:207 +0x24e
  github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes_test.TestKubernetes(0xc00005f400)
  	/workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_suite_test.go:12 +0xf9
  testing.tRunner(0xc00005f400, 0x27c18f0)
  	/usr/local/go/src/testing/testing.go:909 +0x19a
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:960 +0x652
------------------------------
SSSS

Summarizing 1 Failure:

[Fail] Kubernetes kubernetes [It] uses json keys when serializing 
/workspace/gloo/projects/gloo/pkg/plugins/kubernetes/kubernetes_test.go:165
```

Never seen this before... flake?

/kick

**Comment by marcogschmidt** [comment]
Ingress regression test [flake](https://console.cloud.google.com/cloud-build/builds/2fbb842b-6f64-479d-be1f-4ef0d1701848;step=17?project=solo-public). /kick

**Comment by marcogschmidt** [comment]
Regression test [flake](https://console.cloud.google.com/cloud-build/builds/9f18f4b5-be37-4d7e-ae8f-082da46f5928;step=15?project=solo-public)

/kick

**Comment by marcogschmidt** [comment]
Regression test [flake](https://console.cloud.google.com/cloud-build/builds/fc74fa1e-73d0-4389-ac86-d5da1c4b7e25;step=15?project=solo-public)

/kick

**Comment by ashleywang1** [comment]
/kick regression-test flake: gateway_suite_test.go https://console.cloud.google.com/cloud-build/builds/8b74d96d-8f55-42d4-becf-f3a998877e21;step=15?project=solo-public

**Comment by ashleywang1** [comment]
/kick [Fail] Kube2e: gateway tests with virtual service with a mix of valid and invalid virtual services [BeforeEach] adds the invalid virtual services back into the proxy when updating an upstream makes them valid  flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=177b7415-0770-48bc-af57-b593fec921dd

**Pull request merged**
