### PR TITLE
Edit note to show up

### PR DESCRIPTION
**Pull request by artberger**
Follow up to https://github.com/solo-io/gloo/pull/5216, for https://github.com/solo-io/gloo/issues/5171

# Checklist:

- N/A I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- N/A If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- N/A I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by artberger** [comment]
Content shows up in local build:

image

**Review by Rachael-Graham — APPROVED** [review]

**Pull request merged**
