### PR TITLE
Allow helm to install multiple gateways with only one proxy

### PR DESCRIPTION
**Pull request by snuggie12**
Our current installation has a gateway pair (http/https) for both an internal and external gateway-proxy service but points at the same gateway-proxy.

This change allows you to customize everything in order to accomplish that:
- Ability to turn off creating a deployment/pod and default to on
- Ability to turn off the ConfigMap for the extra gateways and default to on
- Ability to turn off creating the service and default to on (we don't need this, but I figured I'd be consistent with all the objects being created from the `gatewayProxies` key.)
- Additionally allow a custom name for the proxy itself. Where as our services are called `gateway-proxy-{internal,external}` the pod is still called `gateway-proxy`
- Allow for custom list of proxies a gateway is applied to.
- Also removed an extraneous indent in the gateway template
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2446

### CODE REVIEW

**Comment by snuggie12** [comment]
I can't add the WIP label, but I just noticed what generate.go does so I need to go edit values.go and add my new keys.

**Comment by ilackarms** [comment]
/test

excellent work! thank you!

**Comment by snuggie12** [comment]
@ilackarms A little confused on why the error. It appears to me that the tests should pick up the new values.yaml that my change should generate. Perhaps it doesn't and I need to add `createDeployment` around line 655 of helm_test.go for the internal proxy to pick up the new value?

**Comment by snuggie12** [comment]
/test

Hoping I have perms to run the test again?

**Comment by marcogschmidt** [comment]
Hi @snuggie12, thanks for the contribution! Could you share an example of the values that you plan to use with this updated chart?

**Comment by snuggie12** [comment]
Yes, that is correct but I'll describe for posterity. It looks like similar to below. We have two proxies (in values referred to as `gateway-proxy-{internal,external}`. External is sort of treated as the default merely because we use the default ports on it. We should probably change this since any given virtual service joins the internal gateway but that is besides the point.

So for external we do all the normal stuff except we tell all the resources to call the proxy `proxy-gateway`. For the internal one, we change the ports, don't create the deployments or configmaps and also point at the same proxy. We do, however, create a secondary service which is using an internal IP load balancer and creates separate listeners.

```
gatewayProxies:
  gateway-proxy-external:
    antiAffinity: false
    configMap:
      data: null
    createConfigMap: true
    createDeployment: true
    createService: true
    customProxyID: gateway-proxy
    extraInitContainersHelper: ""
    extraVolumeHelper: ""
    gatewaySettings:
      customHttpGateway:
        virtualServiceSelector:
          gwExternal: "true"
      customProxyNames:
      - gateway-proxy
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
      image:
        pullPolicy: Always
        repository: gloo-envoy-wrapper
        tag: 1.2.19
      probes: false
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
  gateway-proxy-internal:
    antiAffinity: false
    configMap:
      data: null
    createConfigMap: false
    createDeployment: false
    createService: true
    customProxyID: gateway-proxy
    extraInitContainersHelper: ""
    extraVolumeHelper: ""
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
      customProxyNames:
      - gateway-proxy
      - gateway-fake
    kind:
      deployment:
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 4080
      httpsPort: 4443
      image:
        pullPolicy: Always
        repository: gloo-envoy-wrapper
        tag: 1.2.19
      probes: false
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
```

**Comment by snuggie12** [comment]
I'm not sure whether this change should be there or not, but I figured making this change will ensure that all tags are there.

I fetched tags from upstream and pushed to this branch. It appears as if the command run locally has the correct tag (`v1.3.6-6-g3759edd3`) or at least without the `-dirty`

**Comment by omatsko** [comment]
Please correct me if I'm wrong, but conceptually this looks a bit tricky to me. It looks wrong to create Gateways by specifying Gateway-Proxy definitions, and then disabling generation of default attributes of theirs. As a developer, I read through the declaration and assume that there will be two  proxies, because there are two defined. To figure out that there will be one, I need to spend some time to go into the details of those configurations. With large deployments, it might become a problem.

It would be more clear if resource configuration contained explicit definitions for those Gateways. 

What do you think?

**Comment by marcogschmidt** [comment]
@snuggie12 Thank you for all the information. I tend to share @alexander-klang's concern about the values becoming ambiguous. 

With these changes and the values you provided we would "trick" the `8-default-gateways.yaml` template into generating more than 2 gateways (listeners) for the same proxy by defining additional "fake" `gatewayProxies`. 

I think that this workaround makes it harder to reason about the `gatewayProxies` values and goes against the original intent behind the `8-default-gateways.yaml` template, which is to get first time users quickly up-and-running by offering a simple default setup (create an HTTP and an HTTPS listener for each deployed proxy, so a user can start creating Virtual Services right away). It is not meant to cover more complex configurations. In general we encourage users to manage their own Gloo CRDs (`Gateways`, `VirtualServices`,`RouteTables`) separately from the Gloo chart.

I have been thinking about how we could generate your desired setup and came up with a couple of options.

### Option 1
Open two extra ports on the `gatewayProxy`, disable gateway generation and provide your own 4 `Gateways` (and an additional service). E.g.:

```yaml
gatewayProxies:
  gatewayProxy:
    gatewaySettings:
      disableGeneratedGateways: true # Disable default gateway generation
    configMap:
      data: null
    kind:
      deployment:
        replicas: 1
    podTemplate:
      # The default ports
      httpPort: 8080
      httpsPort: 8443
      extraPorts: # Open two extra ports on the proxy pod
      - containerPort: 4080
        name: internal-http
        protocol: TCP
      - containerPort: 4443
        name: internal-https
        protocol: TCP
    service: # Assuming this is the external service
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
```
 By using these values you open a total of 4 ports on the proxy. You could then create your own chart with 4 Gateways:
```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: external # external-ssl, internal, internal-ssl
  namespace: default
  labels:
    app: gloo
spec:
  bindAddress: "::"
  bindPort: 8080 # 8443, 4080, 4443
  httpGateway: {} # VS selection criteria here
  useProxyProto: false
  ssl: true
  proxyNames:
  - gateway-proxy # all point to the same proxy
```
 and an additional service:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy-internal
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 4080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 4443
    protocol: TCP
    name: https
  selector:
    gateway-proxy-id: gateway-proxy
    gateway-proxy: live
  type: LoadBalancer
```

### Option 2
This uses 2 different deployments for the internal/external proxies, but has the advantage that:
- you should be able to generate everything with just the Gloo chart
- you have the option of scaling the deployments independently to accommodate the internal and external traffic volumes

You can generate this using the following values:
```yaml
gatewayProxies:
  gatewayProxy: # External proxy
    configMap:
      data: null
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      httpPort: 8080
      httpsPort: 8443
      image:
        pullPolicy: Always
        repository: gloo-envoy-wrapper
        tag: 1.3.6
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
  gatewayProxyInternal: # Internal proxy
    configMap:
      data: null
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      httpPort: 4080
      httpsPort: 4443
      image:
        pullPolicy: Always
        repository: gloo-envoy-wrapper
        tag: 1.3.6
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
```

Would any of these two approaches work for you?

**Comment by snuggie12** [comment]
> It would be more clear if resource configuration contained explicit definitions for those Gateways.
> 
> What do you think?

@alexander-klang could you elaborate on this more? You're referring to the gateway CRD? Are you saying also have a `createGatewayCRD` value as well?

@marcogschmidt I agree with your overall sentiment and think option 1 would work for us. However, I don't really feel like this PR breaks that sentiment. For the novice who just wants to get things up and running this breaks nothing. All the defaults were created to do a demo just like it is now. If you are diving in to figure out how this works then you are likely doing something more complex and customized and this enables you to do it while keeping everything in helm.

A compromise might be to do option 1 but still put in the `customProxyID` feature? We can still create a single entry for the internal one with the extra ports and then just create our own custom gateways and the additional service as you said, but still removes the ambiguity of having a service and pod called `gateway-proxy-internal` that an extra service called `gateway-proxy-external` also points to.

**Comment by snuggie12** [comment]
Spoke to @marcogschmidt and decided that option 1 while adding the ability to have a custom service name is far simpler. Closing and will create a new PR.

**Pull request closed without merging**
