### PR TITLE
add glooctl support for istio 1.9.x

### PR DESCRIPTION
**Pull request by lgadban**
# Description

Adds a separate path for `glooctl` integration with istio 1.9.x, similar to https://github.com/solo-io/gloo/pull/3862

The current implementation reuses the existing proxy/agent config and only swaps the version of the proxy image.
However, the default sidecar template from istio 1.9.x is starting to drift.
**Should we render out a more up-to-date config or just leave as-is (which does work)?**

Additionally, the helm template is hardcoded to use istio 1.8.x, **should I update the version for the helm integration**?

I explored the e2e test but it looks like it still running istio 1.7.x so not sure if it's worth changing as part of this PR.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4153

### CODE REVIEW

**Comment by kdorosh** [comment]
@lgadban I would lean towards updating helm to use the new version.

Does the drifting istio config work on older versions of istio? If so, I'd say we should update. If not, happy to leave it as is (as it's working)

**Comment by lgadban** [comment]
@kdorosh So after digging a bit more into the differences, I'm thinking rather than trying to ensure the older versions will work, we can just opt for leaving config as-is and referencing the latest version of the istio proxy.

I could see some use of building different templates for different versions of istio, but since what currently exists in helm today works for 1.8.x and 1.9.x, I'm not sure adding a bunch of helm changes is warranted right now.

I'm now working on updating the docs and helm chart to use the latest proxy `1.9.4` similar to https://github.com/solo-io/gloo/pull/3987

**Review by kdorosh — APPROVED** [review]

**Pull request merged**
