### PR TITLE
V1.3.x generate changelog docs from GitHub

### PR DESCRIPTION
**Pull request by ashleywang1**
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2799

### CODE REVIEW

**Comment by ashleywang1** [comment]
/kick "Copying gs://solo-public-artifacts.solo.io/envoy/v1.4.2/envoy.stripped" error

**Comment by kdorosh** [comment]
/kick ssl 503 flake logs https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=8a764309-f20d-406f-b628-f6fd6eab1bda

**Pull request merged**
