### PR TITLE
Use hostname for hashing

### PR DESCRIPTION
**Pull request by asayah**
# Description

exposing use_hostname_for_hashing, the hostname will be used for hashing when using maglev for example, useful when using multiple host in the upstreams that resolve to the same IP.

## API changes
- Added use_hostname_for_hashing field to LoadBalancerConfig resource
- ...

## Code changes
- exposing use_hostname_for_hashing
- ...

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jbohanon** [comment]
Awesome! Any appetite to expose it as a helm value? I don't even know if we have a helm section for lb config

**Comment by asayah** [comment]
> Awesome! Any appetite to expose it as a helm value? I don't even know if we have a helm section for lb config

LBs are configured per upstream basis, if it was global it would be useful as a helm value

**Comment by asayah** [comment]
> Is there an e2e test we could add to validate this behavior?

I added a test

**Review by jbohanon — APPROVED** [review]
I still think an e2e test validating user-facing behavior would be good but since customer is confirming this build solves their use case, I am good with this merging

**Review by nfuden — APPROVED** [review]

**Pull request merged**
