### PR TITLE
Cert rotation need the force-rotation flag

### PR DESCRIPTION
**Pull request by TomerJLevy**
# Description

This bug completes the CertGen CronJob to enable Cert Rotation

# Context

Users ran into this bug by running the CertGen CronJob and see that it doesn't override the existing secret

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4638

### CODE REVIEW

**Comment by TomerJLevy** [comment]
@elcasteel and @sam-heilbron please help to push this fix. It doesn't perform the rotation without it... Thanks

**Review by sam-heilbron — APPROVED** [review]

**Comment by elcasteel** [comment]
/kick

Since Sam approved, this will merge automatically when CI passes

**Comment by sam-heilbron** [comment]
/kick old logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=cf4d8773-5af1-4301-8082-444f92a8174d

**Comment by sam-heilbron** [comment]
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=2b86488a-ed69-4ee6-beb3-3d281398f603

**Pull request merged**
