### PR TITLE
Add helm values for settings.spec.ratelimitServer #4379 (#8190)

### PR DESCRIPTION
**Pull request by andrzej-talarek**
# Description

ratelimitServer element is missing in Helm Chart.

# Context

RL can't be enabled, when deploying Gloo Edge using Helm Chart.
Cherry pick of https://github.com/solo-io/gloo/pull/8190

# Checklist:

- [*] If I updated APIs (our protos) or helm values, I ran make -B install-go-tools generated-code to ensure there will be no code diff
- [*] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [*] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [*] I have performed a self-review of my own code
- [*] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by andrzej-talarek** [comment]
Sorry, there was a conflict in `values.go` file and I've resolved it manually - putting 4 spaces instead of a tab as padding solution.
Fixed that - no more mismatch there.

**Review by jenshu — APPROVED** [review]

**Pull request merged**
