### PR TITLE
Fix rest eds default 1.6

### PR DESCRIPTION
**Pull request by kdorosh**
# Description

Small update to ensure rest EDS is enabled by default in environments that run off of k8s, add some unit tests to catch previous error.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kdorosh** [comment]
/skip-changelog fixed the existing one instead of adding a new one

**Review by npolshakova — APPROVED** [review]
Looks good!

**Comment by ashleywang1** [comment]
/skip-changelog fixed the existing one instead of adding a new one

**Review by kdorosh — COMMENTED** [review]
lgtm!

**Pull request merged**
