### PR TITLE
Header matching video

### PR DESCRIPTION
**Pull request by ned1313**
In reference to issue #2147 

Updating each example for readability and matching style guide.

Adding video clips for each example.

Add a Next Steps section to push reader towards the other matching rules guides.

### CODE REVIEW

**Comment by mitchdraft** [comment]
@ned1313 , mind addressing this minor comment on this pr: https://github.com/solo-io/gloo/pull/2142#discussion_r364426351
(approved/merged since you had this open)

**Comment by ned1313** [comment]
> 
> 
> @ned1313 , mind addressing this minor comment on this pr: [#2142 (comment)](https://github.com/solo-io/gloo/pull/2142#discussion_r364426351)
> (approved/merged since you had this open)

Fixed.

**Comment by mitchdraft** [comment]
related issue: https://github.com/solo-io/gloo/issues/2149

**Comment by ned1313** [comment]
Removed videos from repo.

**Pull request merged**
