### PR TITLE
Update docker-compose.yaml to reflect v1.8 config changes

### PR DESCRIPTION
**Pull request by laurentquillerou**
# Description

Adress https://github.com/solo-io/gloo/issues/4971

# Context

Bumping from 1.7 w/o the proper folder structure available throws `fatal`

```
{"level":"fatal","ts":"2021-07-06T14:40:02.692Z","logger":"gateway","caller":"setuputils/main_setup.go:88","msg":"error in setup: starting snapshot watch: initial VirtualHostOption list: reading namespace dir: open /data/config/virtualhostoptions/gloo-system: no such file or directory","version":"1.8.0","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:88\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```
```
{"level":"fatal","ts":"2021-07-06T14:40:08.264Z","logger":"gateway","caller":"setuputils/main_setup.go:88","msg":"error in setup: starting snapshot watch: initial RouteOption list: reading namespace dir: open /data/config/routeoptions/gloo-system: no such file or directory","version":"1.8.0","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:88\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"}
```

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by jenshu** [comment]
@laurentquillerou thanks for the contribution! Do you mind also updating this file `docs/content/installation/gateway/development/docker-compose-file/_index.md` to show the updated directory structure (under the section that says "The updated `data` directory structure should look like this")?

**Comment by laurentquillerou** [comment]
@jenshu thanks for the pointer

**Review by jenshu — APPROVED** [review]

**Pull request merged**
