### PR TITLE
Ci Aws Cred update

### PR DESCRIPTION
**Pull request by yuval-k**
Update aws creds to unblock novel aws location internally
Update gke via cloud builders for novel gke kubectl auth plugin features

### CODE REVIEW

**Review by ianmacclancy — APPROVED** [review]

**Review by ben-taussig-solo — DISMISSED** [review]

**Comment by ben-taussig-solo** [comment]
Update AWS credentials for CI

Steps:
 - Create new IAM user with permission to run AWS tests (lambda Invoke, ec2 access, vault)
 - Create access key
 - Write access key file in the format
 - ```
    [default]
    aws_access_key_id = ...
    aws_secret_access_key = ...
    ```
 - Encode the access key using gcloud KMS:
   - ```
      gcloud kms encrypt \
       --location=global \
       --keyring=build \
       --plaintext-file=./access_key.txt \
       --ciphertext-file=./ci/aws_credentials.enc \
       --key=build-key
       --project solo-public
      ```

**Review by ben-taussig-solo — APPROVED** [review]

**Comment by jbohanon** [comment]
If these changes make available the creds for AWS IAM user `gloo-edge-e2e-user` then we can also remove the `Skip` in the AWS tests for the vault integration ([link](https://github.com/solo-io/gloo/blob/cc3a41cd764b0637418720948548eba5b784a88f/test/e2e/vault_test.go#L120))

**Review by jenshu — APPROVED** [review]

**Pull request merged**
