### PR TITLE
Revert "6470 hcm internal address config (#6817)"

### PR DESCRIPTION
**Pull request by jackstine**
This reverts commit ad0db56e73389524bc4c57d3f9dceb763c90d81d.

# Description

Reverting because it is causing issues dependency issues upstream.

# Context

`go-control-plane` was bumped, this caused an issue with upstream using `gloo` as dependency.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/6470

### CODE REVIEW

**Review by sam-heilbron — APPROVED** [review]

**Comment by jackstine** [comment]
/kick. [ Gateway in memory hybrid gateway tcp ssl [It] should work with ssl ](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=36c82413-9143-4df5-a1bb-d7ce79844fdd)

**Comment by jackstine** [comment]
```
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][client] [external/envoy/source/common/http/codec_client.cc:107] [C0] disconnect. resetting 1 pending requests
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][client] [external/envoy/source/common/http/codec_client.cc:139] [C0] request reset
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:214] [C0] destroying stream: 0 remaining
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][router] [external/envoy/source/common/router/router.cc:1198] [C0][S3966959936388581416] upstream reset: reset reason: connection termination, transport failure reason: 
Step #10 - "test": [2022-08-01 18:05:11.098][126656][warning][config] [external/envoy/source/common/config/grpc_stream.h:160] StreamAggregatedResources gRPC config stream closed: 13, 
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:113] gRPC update for type.googleapis.com/envoy.config.listener.v3.Listener failed
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:483] [C0] client disconnected, failure reason: 
Step #10 - "test": [2022-08-01 18:05:11.098][126656][debug][pool] [external/envoy/source/common/conn_pool/conn_pool_base.cc:453] invoking idle callbacks - is_draining_for_deletion_=false
```

**Comment by sam-heilbron** [comment]
The real error is:

```
 ••••Fail handler msg Unexpected error:
Step #10 - "test":     <*errors.resourceVersionErr | 0xc002b333c0>: {
Step #10 - "test":         namespace: "gloo-system",
Step #10 - "test":         name: "gateway-proxy-hybrid",
Step #10 - "test":         given: "2",
Step #10 - "test":         expected: "3",
Step #10 - "test":     }
Step #10 - "test":     invalid resource version gloo-system.gateway-proxy-hybrid given 2, expected 3
Step #10 - "test": occurred
Step #10 - "test": 
Step #10 - "test": ------------------------------
Step #10 - "test": • Failure [1.043 seconds]
Step #10 - "test": Gateway in memory hybrid gateway tcp ssl [It] should work with ssl 
Step #10 - "test": /workspace/gloo/test/e2e/gateway_test.go:1146
Step #10 - "test": 
Step #10 - "test":   Unexpected error:
Step #10 - "test":       <*errors.resourceVersionErr | 0xc002b333c0>: {
Step #10 - "test":           namespace: "gloo-system",
Step #10 - "test":           name: "gateway-proxy-hybrid",
Step #10 - "test":           given: "2",
Step #10 - "test":           expected: "3",
Step #10 - "test":       }
Step #10 - "test":       invalid resource version gloo-system.gateway-proxy-hybrid given 2, expected 3
Step #10 - "test":   occurred
```

**Comment by sam-heilbron** [comment]
Basically we're trying update a resource, but are providing the incorrect current version

**Pull request merged**
