### PR TITLE
Adds Support for TCPRoute Status

### PR DESCRIPTION
**Pull request by danehans**
# Description

Previously, the status of TCPRoute was not getting set. This PR adds support for setting TCPRoute status and managing status conditions. This PR is a cherry-pick of https://github.com/k8sgateway/k8sgateway/pull/10368.

Upstream Issue: https://github.com/k8sgateway/k8sgateway/issues/10365

## API changes

N/A

## Code changes

- `projects/gateway2/proxy_syncer/proxy_syncer_test.go`: Adds a TCPRoute parent ref to existing test cases.
- `projects/gateway2/query/mocks/mock_queries.go`: Moved the GatewayQueries interface mock from the `mirror_test` package since it is now being used by multiple test packages.
- `projects/gateway2/translator/gateway_translator_test.go`: Adds TCPRoute test cases to validate proper status reporting.
- `projects/gateway2/translator/listener/gateway_listener_translator.go`: Removes unused `buildTcpListener` helper function. Updated `buildTcpHost()` helper function to report status through `parentRefReporter`.
- `projects/gateway2/translator/listener/gateway_listener_translator_test.go`: Refactors unit tests to use mocked `GatewayQueries` interface.

## CI changes

N/A

## Docs changes

N/A

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/k8sgateway/k8sgateway/issues/10365

### CODE REVIEW

**Comment by danehans** [comment]
The `Docs / Generate versioned docs site` CI job is failing due to https://github.com/solo-io/gloo/issues/10347.

**Comment by sam-heilbron** [comment]
@danehans I see a test failure/flake (I'm not sure which) around TCPRoutes:
- Logs: https://github.com/solo-io/gloo/actions/runs/11958185993/job/33351948300?pr=10387
```
    --- FAIL: TestK8sGateway/TCPRouteServices (65.70s)
        --- FAIL: TestK8sGateway/TCPRouteServices/TestConfigureTCPRouteBackingDestinationsWithMultiServices (65.70s)
```

Could you look into this as part of this PR? Even if it's not the result of your changes, I figure it helps stabilize CI

**Comment by danehans** [comment]
> Could you look into this as part of this PR? Even if it's not the result of your changes, I figure it helps stabilize CI

I've ran the test multiple times locally and it passes:

```sh
➜  gloo git:(issue_10365) GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore go test -v -timeout 600s ./test/kubernetes/e2e/tests -run ^TestK8sGateway$/^TCPRouteServices$
...
--- PASS: TestK8sGateway (167.74s)
    --- PASS: TestK8sGateway/TCPRouteServices (99.92s)
        --- PASS: TestK8sGateway/TCPRouteServices/TestConfigureTCPRouteBackingDestinationsWithMultiServices (47.93s)
        --- PASS: TestK8sGateway/TCPRouteServices/TestConfigureTCPRouteBackingDestinationsWithSingleService (51.98s)
PASS
ok  	github.com/solo-io/gloo/test/kubernetes/e2e/tests	167.839s
```

Additionally, I have not seen this test fail for the k8sgw equivalent [PR](https://github.com/k8sgateway/k8sgateway/pull/10368).

In the meantime, I'll push a separate PR that adds assertions for GatewayClass, Gateway, and TCPRoute status conditions and update the TCPRoute e2e's to call these assertions. It is difficult to troubleshoot the e2e test failure since `Cleanup()` deletes the resources after test completion. Do other e2e's leverage a mechanism to capture state when an assertion fails before deleting the associated resource?

**Review by josh-pritchard — APPROVED** [review]
Approved since its a cherry pick of previously reviewed PR.

**Comment by danehans** [comment]
> Could you look into this as part of this PR? Even if it's not the result of your changes, I figure it helps stabilize CI

@sam-heilbron I pushed https://github.com/solo-io/gloo/pull/10398 to help with ^

**Pull request merged**
