### PR TITLE
feat: add allowed_upstream_headers_to_append in extauth.proto due to #2983

### LINKED ISSUE #2983: How to add multiple headers with the same name from extauth response to upstream
As mentioned in gloo's documentation: https://docs.solo.io/gloo/1.2.0/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#response, I can set `allowedUpstreamHeaders` to ask gloo to add headers sent from extauth response then send to upstream. But I can't add  multiple headers with the same name becase `Note that coexistent headers will be overridden.`

However, in kubernetes authenticating proxy: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#authenticating-proxy, I have to add multiple headers with the same `--requestheader-group-headers` name if this user belongs to multiple groups.

Any chances that I can use gloo as kubernetes authenticating proxy?

### PR DESCRIPTION
**Pull request by weixiao-huang**
close #2983

# Description

This feature add `allowed_upstream_headers_to_append` options for extauthz

# Context

see  #2983 , also see https://github.com/envoyproxy/envoy/pull/11158

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2983

### CODE REVIEW

**Review by Rachael-Graham — COMMENTED** [review]
docs lgtm

**Review by sam-heilbron — CHANGES_REQUESTED** [review]
Hi @weixiao-huang thanks for the contribution! Could you add a changelog as well as a simple unit test to verify the translation of this API?

**Review by sam-heilbron — APPROVED** [review]

**Pull request merged**
