### PR TITLE
feat(access logging): allow for [REQUEST_WITHOUT_QUERY](https://www.e…

### PR DESCRIPTION
**Pull request by gunnar-solo**
# Description

passthrough feature of Envoy.  We now allow for the [REQUEST_WITHOUT_QUERY](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/formatter/req_without_query/v3/req_without_query.proto) options to be specified in AccessLogs

# Context

https://github.com/solo-io/gloo/issues/5503

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/5503

### CODE REVIEW

**Review by sam-heilbron — COMMENTED** [review]
LGTM! Can we also include the steps used to confirm that with this formatted included that the REQ_WITHOUT_QUERY command operator works as expected?

**Comment by gunnar-solo** [comment]
Validation steps:

## spin up a kind cluster and gloo instance
```
kind create cluster
./ci/deploy-to-kind-cluster.sh
```

## create a suitable gateway config for access logging
```
k apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  proxyNames: 
    - gateway-proxy
  httpGateway: {}
  useProxyProto: false
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          path: /dev/stdout
          stringFormat: >
            [%START_TIME%] "%REQ(:METHOD)% %REQ_WITHOUT_QUERY(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%"
            %RESPONSE_CODE% %RESPONSE_FLAGS% %BYTES_RECEIVED% %BYTES_SENT% %DURATION%
            %RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)% "%REQ(X-FORWARDED-FOR)%" "%REQ(USER-AGENT)%"
            "%REQ(X-REQUEST-ID)%" "%REQ(:AUTHORITY)%" "%UPSTREAM_HOST%"
EOF
```

## observe access logs
```
kubectl --namespace=gloo-system logs --follow deployment/gateway-proxy gateway-proxy
```

## trigger an access log and observe result does not contain query params
```
k port-forward -n gloo-system deploy/gateway-proxy 8080
curl http://localhost:8080/all-pets?q=1234&v=4567
> [2021-11-29T15:54:55.667Z] "GET /all-pets HTTP/1.1" 200 - 0 86 1 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36" "ca4deba6-0067-45b1-ba0c-3f093083dcf1" "localhost:8080" "10.244.0.8:8080"
```

**Review by ben-taussig-solo — APPROVED** [review]
LGTM! I was able to walk through the validation steps without issue

**Pull request merged**
