### PR TITLE
remove duplicated tolower

### PR DESCRIPTION
**Pull request by mjaow**
# Description

Please include a summary of the changes.

`sanitizer.SanitizeNameV2` already do the tolower , no need to repeat it

# Context

`sanitizer.SanitizeNameV2` already do the tolower , no need to repeat it

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kdorosh — CHANGES_REQUESTED** [review]
nice catch, thanks for the pr!

please add a changelog per https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog (type `NON_USER_FACING`) as well as fix the imports in the file (`strings` is no longer used after your change)

**Comment by mjaow** [comment]
> nice catch, thanks for the pr!
> 
> please add a changelog per https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog (type `NON_USER_FACING`) as well as fix the imports in the file (`strings` is no longer used after your change)

sure, will do it

**Review by kdorosh — APPROVED** [review]

**Pull request merged**
