### PR TITLE
fixed spelling on main index.html

### PR DESCRIPTION
**Pull request by christian-posta**
fix a few basic spelling errors on index.html

### CODE REVIEW

**Comment by ilevine** [comment]
The text changes look good - I will let @ilackarms to reply but that is the wrong file to update. 
This file is autogenerated. 
The file you need to change is the solo-io/gloo/blob/master/README.md

**Comment by christian-posta** [comment]
Ah okay great @ilevine and @ilackarms I'll make the text changes in the correct place. Thanks for review!

**Comment by christian-posta** [comment]
So I changed spelling in the correct page now as well as the Makefile; the regex also seemed to be wrong so that's now fixed too; please have a review when you get a sec thanks!

**Comment by ilackarms** [comment]
@christian-posta sorry for the delay on this, you're all good (but the branch will need an update)

**Pull request merged**
