### PR TITLE
Backport option to truncate long status messages to v1.8

### PR DESCRIPTION
**Pull request by elcasteel**
# Description

Original PR: https://github.com/solo-io/gloo/pull/6422#event-6575937583
I needed to update the unit test because it relied on `statusClient` which was introduced after version 1.8

### CODE REVIEW

**Comment by elcasteel** [comment]
/kick not sure why the interactive route test is failing

**Review by jenshu — DISMISSED** [review]

**Review by jenshu — APPROVED** [review]

**Pull request merged**
