### PR TITLE
Add ability to set ExternalTrafficPolicy. 

### PR DESCRIPTION
**Pull request by derrickburns**
Add ability to set ExternalTrafficPolicy.  Set default to Local for gateway.

### CODE REVIEW

**Comment by rickducott** [comment]
Hey @derrickburns, due to some intricacies of how we generate stuff, we need to add this into the `GlooDeployment` Go struct that we use to marshal and unmarshal this yaml:

```
ExternalTrafficPolicy string `json:"externalTrafficPolicy"`
``` 

Struct is defined in `install/helm/gloo/generate/values.go`. 

Also, this is probably a big enough change to warrant adding a changelog entry (for background, see [the docs](https://github.com/solo-io/go-utils/tree/master/changelogutils)). You can add a file (named anything) into the next release directory `changelog/v0.11.2` along the lines of:
```
changelog: 
  - type: NEW_FEATURE
    description: You can now override the ExternalTrafficPolicy for Gloo's deployment in the helm chart.
    issueLink: <some Github issue URL>
```

**Comment by yuval-k** [comment]
/kick - ci flaked 2; i think google cloud is not feeling well

**Comment by rickducott** [comment]
CI is happy... Thanks @derrickburns!

**Comment by christian-posta** [comment]
This is great, @derrickburns thanks for submitting this!

**Pull request merged**
