### PR TITLE
make sure that xds is not restarted on settings change

### PR DESCRIPTION
**Pull request by yuval-k**

### CODE REVIEW

**Comment by yuval-k** [comment]
/kick
```
Finished Step #0 - "check-spelling"
Finished Step #1 - "download-untar-dep-cache"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/wget" failed: exit status 123
```
cc @rickducott

**Comment by yuval-k** [comment]
/kick
```
Finished Step #0 - "check-spelling"
Finished Step #1 - "download-untar-dep-cache"
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/wget" failed: exit status 123
```
cc @rickducott

**Comment by yuval-k** [comment]
/kick
3rd time

**Comment by rickducott** [comment]
gcr outage?

**Comment by yuval-k** [comment]
/kick
no idea :/

**Comment by yuval-k** [comment]
ahh no outage! it's spelling errors just was a bit not clear to see

**Comment by yuval-k** [comment]
/kick
ok @rickducott  this is a real one
```
Step #14 - "build-test-assets": Post https://gcr.io/v2/solo-public/discovery/blobs/uploads/: dial tcp 74.125.142.82:443: i/o timeout
```

**Comment by yuval-k** [comment]
/kick
failure unclear https://console.cloud.google.com/cloud-build/builds/69005f38-74d4-4dbe-b653-5a208bf112b1?project=solo-public&organizationId=325453704078

**Comment by yuval-k** [comment]
/kick
```
Step #17 - "regression-tests-cluster-lock": [91m[1mSummarizing 1 Failure:[0m
Step #17 - "regression-tests-cluster-lock": 
Step #17 - "regression-tests-cluster-lock": [91m[1m[Fail] [0m[90mKube2e: Ingress [0m[91m[1m[It] works [0m
Step #17 - "regression-tests-cluster-lock": [37m/workspace/gopath/src/github.com/solo-io/gloo/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113[0m
Step #17 - "regression-tests-cluster-lock": 
```

**Comment by yuval-k** [comment]
/kick
```
Step #14 - "build-test-assets": Put https://gcr.io/v2/solo-public/gloo-envoy-wrapper/blobs/uploads/ABTmro4GtrnsAZWvul04uBkxra2PhpXayD7uLz3pszVCjD4slYuKXxZR5hfjB_tl1OjeyKoujFVDdll7rXEoqz4dgi18xVtcDQDjNOR4LZAX3lS2hbeYnBaXNj2_pSMyESucPbGoSw8BnroHMxxafjczc45Vkm3yMQxZGQ65uA2PnubY5kqeJ3slFSfw?digest=sha256%3A6e1c4a1fc04caab6dd2787502627221483ab650d8e05fcd1de83f2803a280da6: net/http: TLS handshake timeout
```

**Comment by rickducott** [comment]
* We will be eliminating dependence on GCR shortly. Testing out the solution now. 
* We will be collecting and printing all errors from pods upon regression test failure to help surface what is wrong with things like Ingress
* Unclear why the `test` step failed here

**Pull request merged**
