### PR TITLE
feat(translator): use upstreamMap instead of for loop in upstreams array

### PR DESCRIPTION
**Pull request by weixiao-huang**
# Description

This PR use upstreamMap instead of for loop of array and fixes https://github.com/solo-io/gloo/issues/7973

# Context

see https://github.com/solo-io/gloo/issues/7973

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/7973

### CODE REVIEW

**Review by sam-heilbron — COMMENTED** [review]
@weixiao-huang thanks for the contribution! I like the idea here, and agree that there are some improvements we can introduce to the [UpstreamList.Find](https://github.com/solo-io/gloo/blob/13cf3d5e820cb4efd46a8088ef3e44e8747c1d1e/projects/gloo/pkg/api/v1/upstream.sk.go#L71) functionality which currently iterates over a list instead of a quick lookup in a map.

We have an ongoing issue https://github.com/solo-io/solo-kit/issues/521 to track improving the Find performance not just for Upstreams, but all types. I would rather introduce it collectively than just for a single type.

How about we move forward with the following plan:
1. If you can document the performance gains from this PR alone, you add a comment on this PR outlining the improvement
2. I will migrate the issue I linked into the Gloo repository so there is more awareness around it
3. We close out this PR, and link it in the Gloo issue. Then we use the performance measurements as a way to try to prioritize the value of this work.

How does that sound to you?

**Comment by weixiao-huang** [comment]
Sorry for my delay, I'd like to ask whether I should move this PR to solo-kit or just remain it in gloo? Another question is that which performance gains should I add? Is there a template?

**Comment by sam-heilbron** [comment]
> Sorry for my delay, I'd like to ask whether I should move this PR to solo-kit or just remain it in gloo? Another question is that which performance gains should I add? Is there a template?

We don't have a template unfortunately. Any findings you have can be documented here. For example "i applied X upstreams and Y virtual services, and translation took N seconds before this change and M seconds after this change". if you don't have those numbers that is ok too. I figured any proof of impact would help us argue for prioritizing this work on the Engineering team here.

Once you add those details, or just respond saying you don't have them, I will do the following:
1. Create an issue in Gloo to track this feature request, and link this PR
2. Close this PR

**Comment by weixiao-huang** [comment]
Sorry for my delay, I'll check it and provide details before 31st May.

**Comment by weixiao-huang** [comment]
> Sorry for my delay, I'll check it and provide details before 31st May.

I'm sorry but I'm busy in these days, I'll provide it before 12th June.

**Comment by weixiao-huang** [comment]
It seems not easy to reproduce and get a benchmark. Is there any progress for https://github.com/solo-io/solo-kit/issues/521 ? I've found 404 for https://github.com/solo-io/solo-projects/pull/4077 in this issue. Could I try to add a PR for changing for loop to map more generic in solo-kit?

**Comment by sam-heilbron** [comment]
> It seems not easy to reproduce and get a benchmark. Is there any progress for [solo-io/solo-kit#521](https://github.com/solo-io/solo-kit/issues/521) ? I've found 404 for [solo-io/solo-projects#4077](https://github.com/solo-io/solo-projects/pull/4077) in this issue. Could I try to add a PR for changing for loop to map more generic in solo-kit?

I've created https://github.com/solo-io/gloo/issues/8988 to track this request in a more public space (this repository) so that others who have feedback on the urgency of it, or ideas for solving it can participate. 

Given that this PR is a good start to a solution, but does not solve the problem holistically, I would vote that we close it. If you are interested in trying to solve this issue as written in solo-kit to provide this enhancement, that would be amazing!

**Pull request closed without merging**
