### PR TITLE
wip: add optional loadBalancerIP setting to the knative-external-proxy service

### PR DESCRIPTION
**Pull request by jvdgeest**
This commit adds an optional `loadBalancerIP` setting to the `knative-external-proxy` service, similar to what the `gateway-proxy` already supports. See https://github.com/solo-io/gloo/issues/2778 for the related issue. This allows you to assign a static IP to the Knative external proxy.

I have tested this change on an Azure Kubernetes cluster, and it works. I first deployed Gloo with Helm without this new loadBalancerIP setting:

```yaml
settings:
  integrations:
    knative:
      enabled: true
      version: 0.13.0
```

In Azure, it gets a dynamic assigned IP address. After this, I removed the `knative-external-proxy` service manually, and redeployed the Gloo Helm chart with this new setting:

```yaml
settings:
  integrations:
    knative:
      enabled: true
      version: 0.13.0
      proxy:
        service:
          loadBalancerIP: 20.50.1.1
```

After deployment, I can verify this static loadBalancerIP address is assigned:

```
NAME                             TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                               AGE
service/knative-external-proxy   LoadBalancer   10.2.0.239   20.50.1.1   80:32311/TCP,443:31637/TCP            18m
```

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2778

### CODE REVIEW

**Comment by rickducott** [comment]
Thanks! Sorry for the delay @jvdgeest . One thing we should add is a changelog entry to this PR, kind of like this: https://github.com/solo-io/gloo/blob/47def64762ee52aa0aeae8ce7cf80774533d8ca4/changelog/v1.3.14/gateway-ipv4-only.yaml

**Comment by rickducott** [comment]
/test

CI flake #2859

**Comment by jvdgeest** [comment]
Thanks @rickducott! To which folder (version number) should I add the changelog entry? 

I would suggest something like this for the changelog entry:

```
changelog:
  - type: HELM
    description: >
      Add a helm chart value `settings.integrations.knative.proxy.service.loadBalancerIP`.
      This allows you to assign a static IP to the Knative external proxy.
    issueLink: https://github.com/solo-io/gloo/issues/2778
```

**Comment by kdorosh** [comment]
@jvdgeest `changelog/v1.4.0-beta6/<name-of-changelog.yaml>` is the right changelog location for the next release

**Comment by jvdgeest** [comment]
@kdorosh Thanks, I have added the changelog entry to this pull request.

**Comment by kdorosh** [comment]
/test e2e 503 rate limit flake, https://console.cloud.google.com/cloud-build/builds/41f1a38c-dec0-4459-9026-4f3cad66b267;step=9?project=solo-public

just fixed this in Gloo Enterprise CI, will open a PR to fix in open-source too

**Pull request merged**
