### PR TITLE
Replace Gloo Edge references in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by timflannagan**
# Description

Replaces any references to the old "Gloo Edge" project name with "Gloo" in the CONTRIBUTING.md file. That file is referencing how to contribute to Gloo the repository, so I felt it was appropriate to rename those references, especially after the rebranding for the gateway project. Additionally, the markdown linter in my IDE had several warnings that I fixed along with these changes.

See each individual commit to see what was changed with this branches' overall changes.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jbohanon — CHANGES_REQUESTED** [review]
We should either defer to the prior art [here](https://github.com/solo-io/gloo/pull/9646) and change `Gloo Edge` to `Gloo Gateway` or change the references that were previously changed to match this format.

Internal slack: https://solo-io-corp.slack.com/archives/C03MFATU265/p1724259395064519

**Comment by timflannagan** [comment]
@jbohanon Updated in the latest commit. Sorry for the force push as well, bad habit.

**Review by jbohanon — APPROVED** [review]

**Review by jenshu — APPROVED** [review]

**Review by jenshu — APPROVED** [review]

**Pull request merged**
