### PR TITLE
[1.17] Expose max_buffered_{rx/tx}_bytes in the Tap filter (#9656) (#10016)

### PR DESCRIPTION
**Pull request by andy-fong**
# Description

Backport from #10016 , see origin PR for details

## Docs changes

# Context

## Notes for reviewers

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by andy-fong** [comment]
kick-ci

**Comment by andy-fong** [comment]
There is a "pending" v1.17.8 with some CVE backports. So, piggybacking on this release.

**Review by ashishb-solo — APPROVED** [review]

**Pull request merged**
