### PR TITLE
bump gloo edge versions

### PR DESCRIPTION
**Pull request by bcollard**
# Description

Bump the version in the GH issue templates

### CODE REVIEW

**Review by kcbabo — APPROVED** [review]
Looks good. Thanks for doing this, @bcollard

Should we hold on merging this until Edge 1.10 GA is announced?

**Comment by bcollard** [comment]
> Looks good. Thanks for doing this, @bcollard
> 
> Should we hold on merging this until Edge 1.10 GA is announced?

up to you!

**Comment by kcbabo** [comment]
@sam-heilbron - do you mind merging this once Edge 1.10 GA is announced? I'll swing back and remind you as well - just want to make sure we hold off until the release goes out so users don't get confused.

**Comment by kcbabo** [comment]
@sam-heilbron this is good to go now - 1.10 GA has been announced.

**Pull request merged**
