### PR TITLE
backport topologySpreadConstraints in v1.11.x

### PR DESCRIPTION
**Pull request by Kostavro**
# Description

backport of https://github.com/solo-io/gloo/pull/7597

# Context

Requested (by myself) at https://github.com/solo-io/gloo/issues/7582

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Kostavro** [comment]
@sam-heilbron whenever you can take a look that would be great! Thanks :)

**Review by sam-heilbron — APPROVED** [review]

**Comment by sam-heilbron** [comment]
@Kostavro thanks for opening this! I noticed some issues in build-bot on earlier versions of Gloo Edge so I opened https://github.com/solo-io/gloo/pull/7652 to introduce the same backport but from a non-fork. We should be ok to close this PR.

**Comment by Kostavro** [comment]
Thanks again @sam-heilbron . Shall I close the other 2 backports onto 1.12 and 1.13 as well? Will you handle them?

**Pull request closed without merging**
