### PR TITLE
fix: perform deep-merge on gatewayProxy helm values [3946]

### PR DESCRIPTION
**Pull request by JoshVee**
# Description

Resolves https://github.com/solo-io/gloo/issues/3946 and https://github.com/solo-io/gloo/issues/3142

By performing a deep-merge operation on the Helm dictionary values, we are able to reuse the defaults in `.Values.gatewayProxies.gatewayProxy`.

# Context

This avoids having to manually specify all the values when running multiple gateway proxies. This is especially problematic during upgrades, as the expected helm values may have changed.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by sam-heilbron** [comment]
Thanks for the input @JoshVee! Someone from Solo.io will follow up on this soon.

**Comment by kdorosh** [comment]
test failures look legit, helm2 tests are failing (appears to be bug in helm 2 code? the helm 2 binary works with this, but the golang code for the test fails)

**Comment by kevin-shelaga** [comment]
Helm 3 tests pass, Helm 2 tests fail with " function \"deepCopy\" not defined"

Helm 2.16 added deepCopy, I am wondering if there is a bug with Helm 2.16/17 and rendering charts with deepCopy. Maybe with "k8s.io/helm/pkg/renderutil"

**Comment by kdorosh** [comment]
superseded by https://github.com/solo-io/gloo/pull/4332

**Pull request closed without merging**
