### PR TITLE
Improve Makefile to make outside contributors lives easier

### PR DESCRIPTION
**Pull request by CamelCaseNotation**
Lets a contributor specify one thing in the Makefile to change such that
building and pushing new images for personal use is easier

Add "clean-generated-code" target to Makefile which is required when
making changes to proto files, otherwise `make generated-code -B` target
fails with an exit code, and other targets such as `make gloo` will fail
too.

### CODE REVIEW

**Comment by yuval-k** [comment]
thanks!

**Comment by arianaw66** [comment]
/kick I believe this is a known flake, but I'm checking

**Comment by CamelCaseNotation** [comment]
🎉

**Pull request merged**
