### PR TITLE
fix-knative-manifest-parsing (#1371)

### PR DESCRIPTION
**Pull request by kdorosh**
port of https://github.com/solo-io/gloo/pull/1371 to `feature-rc1`

### CODE REVIEW

**Comment by kdorosh** [comment]
no changelog needed because we "reused" them on master, i.e.:
* https://github.com/solo-io/gloo/blob/master/changelog/v0.20.6/fix-knative-manifest-parsing.yaml
* https://github.com/solo-io/gloo/blob/master/changelog/v0.20.7/fix-knative-manifest-parsing.yaml

So this changelog already exists on `feature-rc1`:
* https://github.com/solo-io/gloo/blob/feature-rc1/changelog/v0.21.0/fix-knative-manifest-parsing.yaml

**Comment by mitchdraft** [comment]
build bot may be linking to incorrect build after kicks
immediately after kick it linked here (correctly): https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=8f9c2fd2-47c1-4eb9-a146-348694073287
- waiting to see if it misaligns after a few minutes as seemed to be the case on prior kick (referenced the first build, not the kicked build)

**Pull request merged**
