### PR TITLE
Fixed VirtualService documentation

### PR DESCRIPTION
**Pull request by iamrajiv**
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/4772

### CODE REVIEW

**Comment by iamrajiv** [comment]
@willowmck Please review.

**Comment by willowmck** [comment]
LGTM

**Comment by sam-heilbron** [comment]
Hi @iamrajiv please add a changelog to your PR per https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog to pass that check, and ensure that our codegen check will pass as well. Thanks for the contribution!

**Comment by sam-heilbron** [comment]
@iamrajiv thanks for the contribution!

**Comment by sam-heilbron** [comment]
Hi @iamrajiv please add a changelog to your PR per https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog to associate the github issue with your PR, and ensure that our codegen check will pass as well, by running `make install-go-tools generated-code`.

**Comment by iamrajiv** [comment]
@sam-heilbron Please review.

**Comment by iamrajiv** [comment]
@sam-heilbron Please review.

**Comment by sam-heilbron** [comment]
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=0d0ed82d-cf4e-4775-9658-39c86e86a887

**Review by saiskee — APPROVED** [review]

**Comment by saiskee** [comment]
Thanks @iamrajiv!

**Pull request merged**
