### PR TITLE
Refactor generated Open Source Attribution docs to markdown files

### PR DESCRIPTION
**Pull request by saiskee**
Publish to docs on push to master previously failed because `osa_provided.docgen` and `osa_included.docgen` were not pushed to github, as they needed to be. They are part of the .gitignore file. This PR adds these two generated files as markdown files.

### CODE REVIEW

**Review by kdorosh — DISMISSED** [review]

**Comment by saiskee** [comment]
code gen is failing because it is trying to build master, however master docs build is broken currently. This will fix this issue on merge to master.

**Review by mlholland — APPROVED** [review]

**Pull request merged**
