### PR TITLE
Expose max_connection_duration via Gloo API

### PR DESCRIPTION
**Pull request by Sodman**
# Description

Exposes `max_connection_duration` and `max_stream_duration` via the Gloo API

# Context

Note `drain_timeout` and `delayed_close_timeout` requested in the linked issue are already exposed in the Gloo API - https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/hcm/hcm.proto#L45-L46

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3628

### CODE REVIEW

**Comment by Sodman** [comment]
/kick AWS timeout - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=bee21212-8266-46ee-b68f-cfa562984575

**Review by kdorosh — CHANGES_REQUESTED** [review]
let's also expose https://github.com/solo-io/gloo/issues/3628#issuecomment-697030107

**Comment by Sodman** [comment]
> let's also expose [#3628 (comment)](https://github.com/solo-io/gloo/issues/3628#issuecomment-697030107)

They're actually already exposed in master! https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/hcm/hcm.proto#L45-L46

**Review by kdorosh — APPROVED** [review]

**Pull request merged**
