### PR TITLE
Fix: Istio mTLS not working in permissive mode

### PR DESCRIPTION
**Pull request by pwoelfle**
# Description

As described in #3994 Gloo Gateway Proxy cannot establish a mTLS connection to an application which uses Istio mTLS in permissive mode.

As solution, the ALPN protocols must be applied when resolving the common ssl config for SDS.

# Context

The user receives the following error when trying to access an application behind the Gloo Gateway Proxy which is secured with Istio mTLS in permissive mode:

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435703:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
```

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/3994

### CODE REVIEW

**Review by kdorosh — APPROVED** [review]

**Comment by kdorosh** [comment]
/skip-ci , previous build passed and the only update since was an API change

**Comment by pwoelfle** [comment]
@kdorosh Thanks for approving and merging.

Will this fix also be merged into older releases? We would need it also on 1.5.x.

**Comment by kdorosh** [comment]
@pwoelfle we can handle those backports

**Comment by npolshakova** [comment]
@pwoelfle The changes are backported and are in the v1.5.20 release.

**Comment by pwoelfle** [comment]
@npolshakova thank you very much 👍🏻

**Pull request merged**
