### PR TITLE
Add single-namespace flag

### PR DESCRIPTION
**Pull request by derrickburns**
This allows easy use of a common use case.

Addresses #948 
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/949

### CODE REVIEW

**Comment by yuval-k** [comment]
Hi @derrickburns !
thank you for this PR. One small ask - can you add the new value to here as well:
https://github.com/solo-io/gloo/blob/master/install/helm/gloo/generate/values.go#L80

we use this to auto-generate the helm chart values docs, here:
https://gloo.solo.io/installation/gateway/kubernetes/#list-of-gloo-helm-chart-values

Thanks!

**Comment by derrickburns** [comment]
@yuval-k will do

**Pull request merged**
