### PR TITLE
Update cookie session to allow use of refresh token 

### PR DESCRIPTION
**Pull request by jmhbh**
# Description
* Modifying the enterprise `extauth` api to allow users to toggle usage of the refresh token when stored as a cookie. This will allow users to set the use of the refresh token in their CRD and allow us to use it in the `ext-auth-service` to issue a new token if the id token has expired.
* Tests/use for this api change can be found in this PR https://github.com/solo-io/ext-auth-service/pull/359
  
# Context

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by jackstine — COMMENTED** [review]
LGTM

**Review by inFocus7 — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
