### PR TITLE
Backport httpconnect headers

### PR DESCRIPTION
**Pull request by kdorosh**
# Description

backport of https://github.com/solo-io/gloo/pull/6946

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by kdorosh** [comment]
/kick flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=7aefbbf5-28c7-422b-9574-cd42f976cc95

**Comment by kdorosh** [comment]
/kick e2e flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=13b183c7-c005-4829-8325-0ec719513a93

**Comment by kdorosh** [comment]
/kick flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=125a7527-f43f-44c1-a699-c5a8a3cadb68

**Comment by kdorosh** [comment]
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d6a2123a-a153-4aba-9835-1a6707170c82

**Review by nfuden — APPROVED** [review]

**Pull request merged**
