### PR TITLE
Go 1.18.1 upgrade

### PR DESCRIPTION
**Pull request by jenshu**
# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by nfuden** [comment]
Looks like regression gateway may be real error ../../../go/pkg/mod/github.com/hashicorp/vault/sdk@v0.1.14-0.20191112033314-390e96e22eb2/helper/compressutil/compress.go:12:2: zip: not a valid zip file

**Comment by jenshu** [comment]
/kick not sure if flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=15c11eec-37ec-4ebf-b00a-47ccf7fa17b7

**Comment by jenshu** [comment]
/kick ssl flake? https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=456d3316-8886-413d-aab9-e86f549e6c6a

**Comment by jenshu** [comment]
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=addc9a7c-01cb-4df9-a0b6-dfa88b119503

**Review by nfuden — APPROVED** [review]

**Pull request merged**
