### PR TITLE
fix: expose isolateVirtualHostsBySslConfig as a values yaml parameter…

### PR DESCRIPTION
**Pull request by gunnar-solo**
Expose isolateVirtualHostsBySslConfig as a values yaml parameter to enable setting it in the settings.yaml

# Context

this PR allows consuming the fix from this issue https://github.com/solo-io/gloo/issues/6677

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by gunnar-solo** [comment]
successor of https://github.com/solo-io/gloo/pull/7090

**Comment by gunnar-solo** [comment]
/kick [Step #10 - "test": [Fail] CSRF defined on listener defined on listener with shadow mode config [It] should succeed with un-allowed origin and update invalid count](https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=aec5c235-b39a-4d67-b8bf-aa761c9b009f)

**Review by ben-taussig-solo — APPROVED** [review]
Looks good!

**Pull request merged**
