### PR TITLE
fix: update Gloo image version in Nomad/Vagrant demo

### PR DESCRIPTION
**Pull request by parkedwards**
# Description

This PR updates the pinned Gloo versions running in the Nomad / Vagrant demo to `1.4.13`

# Context

Running the demo at `/install/nomad/demo-vagrant.sh`, I consistently ran into issues where the Nomad job specifications couldn't complete their placement of all of the Gloo tasks because `gateway-proxy` wouldn't stay healthy:

image

MAY be related to solo-io/gloo#2404

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kdorosh — APPROVED** [review]
thanks for the contribution!

**Comment by parkedwards** [comment]
@kdorosh not sure if this would work, but any chance you wouldn't mind adding a label to this PR post-hoc for Hacktoberfest?

https://hacktoberfest.digitalocean.com/

**Comment by kdorosh** [comment]
I crested and added a label -- appreciate the contribution. Hopefully it can count toward Hacktoberfest

**Pull request merged**
