### PR TITLE
expose envoy's HeaderKeyFormat in the Gloo API

### PR DESCRIPTION
**Pull request by ashleywang1**
# Description

This is a new feature to expose envoy's core.Http1ProtocolOptions.HeaderKeyFormat in the Gloo API as httpConnectionManager.http_protocol_options.proper_case_header_key_format.

From the envoy docs:
By default, all header keys are lower cased. If proper_case_header_key_format is set to true, envoy formats the header by proper casing words: the first character and any character following a special character will be capitalized if it’s an alpha character. For example, “content-type” becomes “Content-Type”, and “foo$b#$are” becomes “Foo$B#$Are”. Note that while this results in most headers following conventional casing, certain headers are not covered. For example, the “TE” header will be formatted as “Te”.

# Context

https://github.com/solo-io/gloo/issues/2940

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make update-deps generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2940

### CODE REVIEW

**Comment by ashleywang1** [comment]
Based on discussion: The requirement is to preserve the case of the response headers in the same format as it was originally received from the upstream. We do not want envoy or gloo to change the original case of the response headers.

So this PR may be invalid.

**Comment by kdorosh** [comment]
/kick regression test flake https://console.cloud.google.com/cloud-build/builds/3f191687-bdac-416d-b813-84f3a4a76f78?project=solo-public

**Comment by kdorosh** [comment]
/kick could not render proxy regression test flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=3e08735f-03d0-4407-917e-fddc25043430

**Pull request merged**
