### PR TITLE
Fix doc workflow

### PR DESCRIPTION
**Pull request by artberger**
# Description

Noticed that the doc workflow was using deprecated GitHub Action features:
* `set-output`, changed to environment variables, see blog: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* outdated action versions, bumped to `v3`, see blog: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

image

# Other unsolved failure
Example of recent `Generate versioned doc site` job failure: https://github.com/solo-io/gloo/actions/runs/3752721633

Not addressed in this PR because I'm not sure what this failure means. Saw this StackOverflow [post](https://stackoverflow.com/questions/5989592/git-cannot-checkout-branch-error-pathspec-did-not-match-any-files-kn), but this build previously worked and we haven't changed the steps for fetching the remote, so not sure why that would be the case. 
```
+ make site-release
make[1]: Entering directory '/home/runner/work/gloo/gloo/docs/gloo-temp/docs'
rm -fr ./site ./resources ./site-latest ./site-versioned ./public ./ci ./gloo-temp ./themes
cd .. && GO111MODULE=on go run hack/find_latest_enterprise_version.go
if [ ! -d themes/hugo-theme-soloio ]; then git clone https://github.com/solo-io/hugo-theme-soloio themes/hugo-theme-soloio; fi
Cloning into 'themes/hugo-theme-soloio'...
git -C themes/hugo-theme-soloio checkout null
error: pathspec 'null' did not match any file(s) known to git
make[1]: *** [Makefile:30: site-common] Error 1
make[1]: Leaving directory '/home/runner/work/gloo/gloo/docs/gloo-temp/docs'
make: *** [Makefile:91: build-site] Error 2
make: Leaving directory '/home/runner/work/gloo/gloo/docs'
Error: Process completed with exit code 2.
```

# Context

Doc workflow was failing several times in a row. See Slack: https://solo-io-corp.slack.com/archives/C0311V0FFJ9/p1671565846735149

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- N/A If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- N/A I have performed a self-review of my own code
- N/A I have commented my code, particularly in hard-to-understand areas
- N/A I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by sam-heilbron — APPROVED** [review]

**Review by sam-heilbron — APPROVED** [review]

**Review by nfuden — APPROVED** [review]

**Review by sam-heilbron — CHANGES_REQUESTED** [review]
Looks like the GHA to build the docs is being skipped with these changes

**Comment by ben-taussig-solo** [comment]
Regarding the unsolved failure: We have this line in the docs makefile to try and get the most recent tag of the solo io Hugo theme: https://github.com/solo-io/gloo/blob/v1.14.0-beta2/docs/Makefile#L8 -- it looks like for whatever reason that tag is null, so we get an error here when we try to checkout that tag: https://github.com/solo-io/gloo/blob/v1.14.0-beta2/docs/Makefile#L30

**Comment by artberger** [comment]
@ben-taussig-solo yeah, the v0.0.22 is the [latest](https://github.com/solo-io/hugo-theme-soloio/releases), and was released in September, so it's odd the builds just started failing on this null issue a lot this past week. 

The Platform repo uses the same [checkout curl](https://github.com/solo-io/gloo-mesh-enterprise/blob/main/docs/Makefile#L22), and most of those [doc builds](https://github.com/solo-io/gloo-mesh-enterprise/actions/workflows/publish_docs_preview.yaml?page=2) are passing, although we have seen some of those `null` checkout errors like [here](https://github.com/solo-io/gloo-mesh-enterprise/actions/runs/3752923222/jobs/6375630781#step:14:205) or some auth ones like [here](https://github.com/solo-io/gloo-mesh-enterprise/actions/runs/3753335342/jobs/6377028505#step:9:927). (Not sure if this is helpful context or just extra noise 😅 )

**Review by sam-heilbron — APPROVED** [review]

**Pull request merged**
